[Appearance]
custom_palette=true
color_scheme_path=~/.config/qt6ct/colors/ryoku.conf
icon_theme=Papirus-Dark
standard_dialogs=default
style=Fusion

[Fonts]
general="Space Grotesk,10,-1,5,50,0,0,0,0,0"
fixed="SpaceMono Nerd Font,10,-1,5,50,0,0,0,0,0"
