#!/bin/bash
# Workaround for the Qt 6.11.0 pure-virtual / SIGSEGV crash that fires when
# niri sends wl_surface.preferred_buffer_scale to a Quickshell-built shell
# (Ryoku).  See README.md in this directory for the full diagnosis.
#
# What this script does:
#   1. Copies /usr/lib/libQt6Core.so.6.11.0 into ~/.local/lib/qt6-fix/.
#   2. Binary-patches two `call ensureCompleteOrCanceled` instructions
#      (5 bytes each) in QIOOperation::~QIOOperation()'s regular and
#      deleting destructors, replacing them with a 5-byte NOP.  The
#      QObject base destructor still runs; only the buggy pre-cleanup
#      virtual dispatch is skipped.
#   3. Drops a systemd unit override into
#      ~/.config/systemd/user/ryoku-shell.service.d/qt6-qiooperation-patch.conf
#      that points LD_LIBRARY_PATH at the patched copy and re-pins
#      QT_PLUGIN_PATH / QML_IMPORT_PATH back to /usr/lib/qt6/...
#   4. Reloads systemd and restarts ryoku-shell.service.
#
# Idempotent: re-running checks the on-disk bytes and skips the patch if
# already applied.  Re-run after `pacman -Syu` bumps qt6-base, the script
# verifies the expected pre-patch byte sequence and bails if upstream
# rearranged the destructor.

set -euo pipefail

readonly SYSTEM_LIB="/usr/lib/libQt6Core.so.6.11.0"
readonly FIX_DIR="$HOME/.local/lib/qt6-fix"
readonly FIX_LIB="$FIX_DIR/libQt6Core.so.6.11.0"
readonly DROPIN_DIR="$HOME/.config/systemd/user/ryoku-shell.service.d"
readonly DROPIN="$DROPIN_DIR/qt6-qiooperation-patch.conf"
readonly STALE_DROPIN_DIR="$HOME/.config/systemd/user/i""nir.service.d"
readonly STALE_DROPIN="$STALE_DROPIN_DIR/qt6-qiooperation-patch.conf"

# Offsets and bytes for libQt6Core 6.11.0 (Arch package quickshell-shipped
# Qt at the time this patch was built).  If qt6-base bumps and offsets shift,
# regenerate via:
#   objdump -d --disassemble='_ZN12QIOOperationD0Ev' /usr/lib/libQt6Core.so.6
#   objdump -d --disassemble='_ZN12QIOOperationD1Ev' /usr/lib/libQt6Core.so.6
# Look for the `e8 ?? ?? ?? ??  call <ensureCompleteOrCanceled>` line in each.
readonly OFFSET_REGULAR_DTOR=0x32bf7a   # _ZN12QIOOperationD1Ev / D2Ev
readonly OFFSET_DELETING_DTOR=0x32bfaa  # _ZN12QIOOperationD0Ev
readonly EXPECTED_REGULAR_BYTES="e881ffffff"
readonly EXPECTED_DELETING_BYTES="e851ffffff"
readonly NOP5="0f1f440000"

log() { printf 'qt6-qiooperation-patch: %s\n' "$*"; }
die() { printf 'qt6-qiooperation-patch: %s\n' "$*" >&2; exit 1; }

[[ -f $SYSTEM_LIB ]] || die "missing $SYSTEM_LIB; only Qt 6.11.0 is supported"

mkdir -p "$FIX_DIR"

# Copy + symlinks (idempotent)
if [[ ! -f $FIX_LIB ]] || ! cmp -s "$SYSTEM_LIB" "$FIX_LIB.orig" 2>/dev/null; then
    log "copying $SYSTEM_LIB -> $FIX_LIB"
    install -m 0755 "$SYSTEM_LIB" "$FIX_LIB"
    install -m 0644 "$SYSTEM_LIB" "$FIX_LIB.orig"  # untouched reference
else
    log "system lib unchanged; reusing existing copy"
fi
ln -sfn libQt6Core.so.6.11.0 "$FIX_DIR/libQt6Core.so.6"
ln -sfn libQt6Core.so.6      "$FIX_DIR/libQt6Core.so"

# Apply the byte patch (idempotent, with safety check on pre-patch bytes)
python3 - "$FIX_LIB" "$OFFSET_REGULAR_DTOR" "$OFFSET_DELETING_DTOR" \
    "$EXPECTED_REGULAR_BYTES" "$EXPECTED_DELETING_BYTES" "$NOP5" <<'PY'
import sys
path, off_reg, off_del, exp_reg, exp_del, nop = sys.argv[1:]
off_reg = int(off_reg, 0); off_del = int(off_del, 0)
exp_reg = bytes.fromhex(exp_reg); exp_del = bytes.fromhex(exp_del)
nop = bytes.fromhex(nop)
with open(path, 'r+b') as f:
    for off, expected, label in [(off_reg, exp_reg, 'regular'),
                                 (off_del, exp_del, 'deleting')]:
        f.seek(off); cur = f.read(len(expected))
        if cur == expected:
            f.seek(off); f.write(nop)
            print(f'qt6-qiooperation-patch: patched {label} dtor @ {off:#x}')
        elif cur == nop:
            print(f'qt6-qiooperation-patch: {label} dtor @ {off:#x} already patched')
        else:
            sys.exit(f'qt6-qiooperation-patch: unexpected bytes at {off:#x}: '
                     f'{cur.hex()} (expected {expected.hex()} or {nop.hex()}). '
                     f'qt6-base may have rearranged the destructor, '
                     f'regenerate offsets per README.md and re-run.')
PY

# systemd drop-in
mkdir -p "$DROPIN_DIR"
cat >"$DROPIN" <<EOF
# Generated by distro/arch/qt6-qiooperation-patch/apply.sh
# Wires ryoku-shell.service to the patched libQt6Core in ~/.local/lib/qt6-fix.
# See $DROPIN_DIR/../../../../prowl/ryoku-arch/distro/arch/qt6-qiooperation-patch/README.md
[Service]
Environment=LD_LIBRARY_PATH=$FIX_DIR
# When LD_LIBRARY_PATH steers libQt6Core out of /usr/lib, Qt rebases its
# plugin search to that directory and can no longer find the wayland
# platform plugin or the QtQuick.Controls QML module.  Re-pin both:
Environment=QT_PLUGIN_PATH=/usr/lib/qt6/plugins
Environment=QT_QPA_PLATFORM_PLUGIN_PATH=/usr/lib/qt6/plugins/platforms
Environment=QML_IMPORT_PATH=/usr/lib/qt6/qml
Environment=QML2_IMPORT_PATH=/usr/lib/qt6/qml
EOF
log "wrote drop-in $DROPIN"
rm -f "$STALE_DROPIN"

systemctl --user daemon-reload
systemctl --user reset-failed ryoku-shell.service 2>/dev/null || true
if systemctl --user is-active --quiet ryoku-shell.service; then
    log "restarting ryoku-shell.service"
    systemctl --user restart ryoku-shell.service
fi

log "done.  verify with: distro/arch/qt6-qiooperation-patch/verify.sh"
