exec-once = uwsm-app -- hypridle
exec-once = uwsm-app -- mako
exec-once = uwsm-app -- wl-paste --type text --watch cliphist store
exec-once = uwsm-app -- wl-paste --type image --watch cliphist store
exec-once = uwsm-app -- swaybg -i ~/.config/ryoku/current/background -m fill
exec-once = ! ryoku-toggle-enabled waybar-off && uwsm-app -- waybar
exec-once = ! ryoku-toggle-enabled frame-off && uwsm-app -- ryoku-launch-shell
exec-once = uwsm-app -- fcitx5 --disable notificationitem
exec-once = uwsm-app -- swayosd-server
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = ryoku-cmd-first-run
exec-once = ryoku-powerprofiles-init
exec-once = ryoku-hyprland-monitor-internal recover
exec-once = uwsm-app -- ryoku-hyprland-monitor-watch

# Slow app launch fix -- set systemd vars
exec-once = systemctl --user import-environment $(env | cut -d'=' -f 1)
exec-once = dbus-update-activation-environment --systemd --all
