#!/usr/bin/env bash
set -euo pipefail

use_ryoku_helpers() {
  export RYOKU_PATH="/root/ryoku"
  export RYOKU_INSTALL="/root/ryoku/install"
  export RYOKU_INSTALL_LOG_FILE="/var/log/ryoku-install.log"
  export RYOKU_MIRROR="$(cat /root/ryoku_mirror)"
  source /root/ryoku/install/helpers/all.sh
}

run_configurator() {
  set_tokyo_night_colors
  ./configurator
  export RYOKU_USER="$(jq -r '.users[0].username' user_credentials.json)"
}

install_arch() {
  clear_logo
  gum style --foreground 3 --padding "1 0 0 $PADDING_LEFT" "Installing..."
  echo

  touch /var/log/ryoku-install.log

  start_log_output

  # Set CURRENT_SCRIPT for the trap to display better when nothing is returned for some reason
  CURRENT_SCRIPT="install_base_system"
  install_base_system > >(sed -u 's/\x1b\[[0-9;]*[a-zA-Z]//g' >>/var/log/ryoku-install.log) 2>&1
  unset CURRENT_SCRIPT
  stop_log_output
}

install_ryoku() {
  chroot_bash -lc "sudo pacman -S --noconfirm --needed gum" >/dev/null
  chroot_bash -lc "source /home/$RYOKU_USER/.local/share/ryoku/install.sh || bash"

  # Reboot if requested by installer
  if [[ -f /mnt/var/tmp/ryoku-install-completed ]]; then
    reboot
  fi
}

# Set Tokyo Night color scheme for the terminal
set_tokyo_night_colors() {
  if [[ $(tty) == "/dev/tty"* ]]; then
    # Tokyo Night color palette
    echo -en "\e]P01a1b26" # black (background)
    echo -en "\e]P1f7768e" # red
    echo -en "\e]P29ece6a" # green
    echo -en "\e]P3e0af68" # yellow
    echo -en "\e]P47aa2f7" # blue
    echo -en "\e]P5bb9af7" # magenta
    echo -en "\e]P67dcfff" # cyan
    echo -en "\e]P7a9b1d6" # white
    echo -en "\e]P8414868" # bright black
    echo -en "\e]P9f7768e" # bright red
    echo -en "\e]PA9ece6a" # bright green
    echo -en "\e]PBe0af68" # bright yellow
    echo -en "\e]PC7aa2f7" # bright blue
    echo -en "\e]PDbb9af7" # bright magenta
    echo -en "\e]PE7dcfff" # bright cyan
    echo -en "\e]PFc0caf5" # bright white (foreground)

    # Set default foreground and background
    echo -en "\033[0m"
    clear
  fi
}

install_base_system() {
  # Initialize and populate the keyring. omarchy also populates the
  # `omarchy` keyring here; we skip it because we do not yet ship a
  # signed [ryoku] custom repo.
  pacman-key --init
  pacman-key --populate archlinux

  # Sync the offline database so pacman can find packages
  pacman -Sy --noconfirm

  # Ensure that no mounts exist from past install attempts
  findmnt -R /mnt >/dev/null && umount -R /mnt

  # Workarounds for archinstall 4.2 regressions under Python 3.14:
  # 1. sync_log_to_install_medium: `self.target / absolute_logfile` drops
  #    self.target because the RHS is absolute, so Path.copy() raises EINVAL
  #    (source == target).
  # 2. _add_limine_bootloader: `Path.copy(efi_dir_path)` raises IsADirectoryError
  #    because 3.14's Path.copy treats target as a literal path, not a directory
  #    (shutil.copy used to auto-append the source filename).
  sed -i \
    -e 's|logfile_target = self\.target / absolute_logfile$|logfile_target = self.target / absolute_logfile.relative_to("/")|' \
    -e 's|(limine_path / file)\.copy(efi_dir_path)|(limine_path / file).copy(efi_dir_path / file)|' \
    -e "s|(limine_path / 'limine-bios.sys')\.copy(boot_limine_path)|(limine_path / 'limine-bios.sys').copy(boot_limine_path / 'limine-bios.sys')|" \
    /usr/lib/python3.14/site-packages/archinstall/lib/installer.py

  # Install using files generated by the ./configurator
  # Skip NTP and WKD sync since we're offline (keyring is pre-populated in ISO)
  archinstall \
    --config user_configuration.json \
    --creds user_credentials.json \
    --silent \
    --skip-ntp \
    --skip-wkd \
    --skip-wifi-check

  # After archinstall sets up the base system but before our installer runs,
  # we need to ensure the offline pacman.conf is in place
  cp /etc/pacman.conf /mnt/etc/pacman.conf

  # Mount the offline mirror so it's accessible in the chroot
  mkdir -p /mnt/var/cache/ryoku/mirror/offline
  mount --bind /var/cache/ryoku/mirror/offline /mnt/var/cache/ryoku/mirror/offline

  # Mount the packages dir so it's accessible in the chroot
  mkdir -p /mnt/opt/packages
  mount --bind /opt/packages /mnt/opt/packages

  # No need to ask for sudo during the installation (ryoku itself responsible for removing after install)
  mkdir -p /mnt/etc/sudoers.d
  cat >/mnt/etc/sudoers.d/99-ryoku-installer <<EOF
root ALL=(ALL:ALL) NOPASSWD: ALL
%wheel ALL=(ALL:ALL) NOPASSWD: ALL
$RYOKU_USER ALL=(ALL:ALL) NOPASSWD: ALL
EOF
  chmod 440 /mnt/etc/sudoers.d/99-ryoku-installer

  # Copy the local ryoku repo to the user's home directory
  mkdir -p /mnt/home/$RYOKU_USER/.local/share/
  cp -r /root/ryoku /mnt/home/$RYOKU_USER/.local/share/

  chown -R 1000:1000 /mnt/home/$RYOKU_USER/.local/

  # Ensure all necessary scripts are executable
  find /mnt/home/$RYOKU_USER/.local/share/ryoku -type f -path "*/bin/*" -exec chmod +x {} \;
  chmod +x /mnt/home/$RYOKU_USER/.local/share/ryoku/boot.sh 2>/dev/null || true
  chmod +x /mnt/home/$RYOKU_USER/.local/share/ryoku/default/waybar/indicators/screen-recording.sh 2>/dev/null || true
  chmod +x /mnt/home/$RYOKU_USER/.local/share/ryoku/default/waybar/indicators/idle.sh 2>/dev/null || true
  chmod +x /mnt/home/$RYOKU_USER/.local/share/ryoku/default/waybar/indicators/notification-silencing.sh 2>/dev/null || true
}

chroot_bash() {
  HOME=/home/$RYOKU_USER \
    arch-chroot -u $RYOKU_USER /mnt/ \
    env RYOKU_CHROOT_INSTALL=1 \
    RYOKU_USER_NAME="$(<user_full_name.txt)" \
    RYOKU_USER_EMAIL="$(<user_email_address.txt)" \
    RYOKU_MIRROR="$RYOKU_MIRROR" \
    USER="$RYOKU_USER" \
    HOME="/home/$RYOKU_USER" \
    /bin/bash "$@"
}

if [[ $(tty) == "/dev/tty1" ]]; then
  use_ryoku_helpers
  run_configurator
  install_arch
  install_ryoku
fi
