# woke config. defaults apply. paths below are skipped: vendored upstream,
# binary blobs, or verbatim license text we didn't write.
ignore_files:
  - ryoku/lockscreen/qylock/**
  - ryoku/assets/**
  - LICENSE
  - LICENSES/**
  - NOTICE
  - "**/*.svg"
  - "**/*.png"
  - "**/*.jpg"
  - "**/*.webp"
  - "**/*.ttf"
