pragma Singleton

import QtQuick
import Quickshell
import Quickshell.Io
import qs.utils

// RYOKU: user-defined desktop widgets. Each widget is a folder under
// ~/.config/ryoku-shell/desktop-widgets/<id>/ with manifest.json + widget.qml.
// This service scans that folder, exposes `list` (one cfg object per widget that
// Background.qml renders inside a DesktopWidget), and writes widgets created from
// the settings creator. See docs/superpowers/specs/2026-05-28-custom-desktop-widgets-design.md.
Singleton {
    id: root

    readonly property string dir: `${Paths.config}/desktop-widgets`

    // Array of per-widget cfg objects (see cfgComponent). Rebuilt on rescan.
    property var list: []

    function _b64(s: string): string {
        // UTF-8 safe base64 (handles unicode in user text/QML).
        return Qt.btoa(unescape(encodeURIComponent(s)));
    }

    function _slug(name: string): string {
        let s = String(name).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
        return s.length > 0 ? s : "widget";
    }

    function _uniqueId(base: string): string {
        const taken = {};
        for (let i = 0; i < root.list.length; i++)
            taken[root.list[i].cwId] = true;
        if (!taken[base])
            return base;
        let n = 2;
        while (taken[`${base}-${n}`])
            n++;
        return `${base}-${n}`;
    }

    function _manifestOf(cfg): var {
        return {
            "schemaVersion": 1,
            "id": cfg.cwId,
            "name": cfg.cwName,
            "type": cfg.cwType,
            "enabled": cfg.enabled,
            "background": cfg.background,
            "scale": cfg.scale,
            "locked": cfg.locked,
            "freePosition": cfg.freePosition,
            "position": cfg.position,
            "x": cfg.x,
            "y": cfg.y,
            "generated": cfg.generated,
            "params": cfg.params
        };
    }

    // Persist a single widget's manifest (geometry / lock / enabled). Fire-and-forget;
    // the in-memory cfg already reflects the change, so no rescan is needed.
    function _persistManifest(cfg): void {
        const b64 = root._b64(JSON.stringify(root._manifestOf(cfg), null, 2));
        const path = `${root.dir}/${cfg.cwId}/manifest.json`;
        Quickshell.execDetached(["sh", "-c", `mkdir -p "${root.dir}/${cfg.cwId}" && printf %s '${b64}' | base64 -d > "${path}"`]);
    }

    function _bgHeader(bg: bool): string {
        return bg ? `    radius: 14
    color: Qt.alpha(Colours.palette.m3surfaceContainer, 0.78)
    border.width: 1
    border.color: Qt.alpha(Colours.palette.m3outlineVariant, 0.6)` : `    radius: 0
    color: "transparent"`;
    }

    function _genText(params, bg: bool): string {
        const text = JSON.stringify(params.text || "Text");
        const color = JSON.stringify(params.color || "#ffffff");
        const fs = Number(params.fontSize) || 24;
        return `import QtQuick
import qs.components
import qs.services

// Generated by the Ryoku custom-widget creator (type: text). Edit freely — once
// you change this file by hand, set "generated": false in manifest.json so the
// creator stops overwriting it.
StyledRect {
    implicitWidth: label.implicitWidth + 28
    implicitHeight: label.implicitHeight + 18
${root._bgHeader(bg)}

    StyledText {
        id: label
        anchors.centerIn: parent
        text: ${text}
        color: ${color}
        font.pointSize: ${fs}
    }
}
`;
    }

    function _genCommand(params, bg: bool): string {
        const cmd = JSON.stringify(params.command || "echo hello");
        const color = JSON.stringify(params.color || "#ffffff");
        const fs = Number(params.fontSize) || 18;
        const ms = Math.max(1, Number(params.intervalSec) || 5) * 1000;
        return `import QtQuick
import Quickshell.Io
import qs.components
import qs.services

// Generated by the Ryoku custom-widget creator (type: command). Runs a shell
// command on an interval and shows its output. Edit freely — once changed by hand,
// set "generated": false in manifest.json so the creator stops overwriting it.
StyledRect {
    id: w
    property string out: ""
    implicitWidth: label.implicitWidth + 28
    implicitHeight: label.implicitHeight + 18
${root._bgHeader(bg)}

    StyledText {
        id: label
        anchors.centerIn: parent
        text: w.out.length > 0 ? w.out : "…"
        color: ${color}
        font.pointSize: ${fs}
    }

    Process {
        id: proc
        command: ["sh", "-c", ${cmd}]
        stdout: StdioCollector {
            onStreamFinished: w.out = text.trim()
        }
    }

    Timer {
        interval: ${ms}
        running: true
        repeat: true
        triggeredOnStart: true
        onTriggered: proc.running = true
    }
}
`;
    }

    function _renderQml(type: string, params, bg: bool, rawQml: string): string {
        if (type === "command")
            return root._genCommand(params, bg);
        if (type === "qml")
            return rawQml && rawQml.length > 0 ? rawQml : root.starterQml();
        return root._genText(params, bg);
    }

    function starterQml(): string {
        return `import QtQuick
import qs.components
import qs.services

// Custom desktop widget. The root item should size itself to its content
// (implicitWidth/Height). Available imports include QtQuick, Quickshell.Io,
// qs.components (StyledRect, StyledText, MaterialIcon), and qs.services (Colours).
// WARNING: this runs as part of the shell with full privileges.
StyledRect {
    implicitWidth: label.implicitWidth + 28
    implicitHeight: label.implicitHeight + 18
    radius: 14
    color: Qt.alpha(Colours.palette.m3surfaceContainer, 0.78)
    border.width: 1
    border.color: Qt.alpha(Colours.palette.m3outlineVariant, 0.6)

    StyledText {
        id: label
        anchors.centerIn: parent
        text: "Hello"
        color: Colours.palette.m3onSurface
        font.pointSize: 20
    }
}
`;
    }

    // opts: { name, type, background, params, qml (raw, for type:"qml") }
    function create(opts): void {
        const id = root._uniqueId(root._slug(opts.name));
        const type = opts.type || "text";
        const manifest = {
            "schemaVersion": 1,
            "id": id,
            "name": opts.name || id,
            "type": type,
            "enabled": true,
            "background": opts.background !== false,
            "scale": 1.0,
            "locked": false,
            "freePosition": false,
            "position": "center",
            "x": 0,
            "y": 0,
            "generated": type !== "qml",
            "params": opts.params || ({})
        };
        const qml = root._renderQml(type, manifest.params, manifest.background, opts.qml);
        root._writeWidget(id, manifest, qml);
    }

    function update(id: string, opts): void {
        const existing = root.find(id);
        if (!existing)
            return;
        const type = opts.type || existing.cwType;
        const manifest = root._manifestOf(existing);
        manifest.name = opts.name || existing.cwName;
        manifest.type = type;
        manifest.background = opts.background !== undefined ? opts.background : existing.background;
        manifest.params = opts.params || existing.params;
        // Editing a generated widget regenerates its QML; raw-QML widgets keep theirs
        // unless new QML is supplied.
        manifest.generated = type !== "qml";
        let qml;
        if (type === "qml")
            qml = (opts.qml && opts.qml.length > 0) ? opts.qml : null;
        else
            qml = root._renderQml(type, manifest.params, manifest.background, null);
        root._writeWidget(id, manifest, qml);
    }

    function _writeWidget(id: string, manifest, qml): void {
        const b64m = root._b64(JSON.stringify(manifest, null, 2));
        let cmd = `mkdir -p "${root.dir}/${id}" && printf %s '${b64m}' | base64 -d > "${root.dir}/${id}/manifest.json"`;
        if (qml !== null && qml !== undefined) {
            const b64q = root._b64(qml);
            cmd += ` && printf %s '${b64q}' | base64 -d > "${root.dir}/${id}/widget.qml"`;
        }
        opProc.command = ["sh", "-c", cmd];
        opProc.running = true;
    }

    function remove(id: string): void {
        // id is a sanitized slug; guard against empty just in case.
        if (!id || id.indexOf("/") !== -1 || id === "." || id === "..")
            return;
        opProc.command = ["sh", "-c", `rm -rf "${root.dir}/${id}"`];
        opProc.running = true;
    }

    function setEnabled(id: string, en: bool): void {
        const cfg = root.find(id);
        if (!cfg)
            return;
        cfg.enabled = en;
        cfg.save();
    }

    function find(id: string): var {
        for (let i = 0; i < root.list.length; i++)
            if (root.list[i].cwId === id)
                return root.list[i];
        return null;
    }

    function rescan(): void {
        if (!scanProc.running)
            scanProc.running = true;
    }

    function _rebuild(manifests): void {
        // Destroy old cfg objects.
        for (let i = 0; i < root.list.length; i++) {
            if (root.list[i])
                root.list[i].destroy();
        }
        const out = [];
        for (let j = 0; j < manifests.length; j++) {
            const m = manifests[j] || {};
            if (!m.id)
                continue;
            const cfg = cfgComponent.createObject(root, {
                "cwId": m.id,
                "cwName": m.name || m.id,
                "cwType": m.type || "text",
                "generated": m.generated !== false,
                "params": m.params || ({}),
                "enabled": m.enabled !== false,
                "background": m.background !== false,
                "scale": (typeof m.scale === "number") ? m.scale : 1.0,
                "locked": m.locked === true,
                "freePosition": m.freePosition === true,
                "position": m.position || "center",
                "x": (typeof m.x === "number") ? m.x : 0,
                "y": (typeof m.y === "number") ? m.y : 0
            });
            if (cfg)
                out.push(cfg);
        }
        root.list = out;
    }

    Component.onCompleted: root.rescan()

    Component {
        id: cfgComponent
        QtObject {
            property string cwId
            property string cwName
            property string cwType: "text"
            property bool generated: true
            property var params: ({})
            // Geometry/state consumed by DesktopWidget:
            property real x: 0
            property real y: 0
            property real scale: 1.0
            property bool locked: false
            property bool freePosition: false
            property string position: "center"
            property bool enabled: true
            property bool background: true
            readonly property string widgetUrl: `file://${root.dir}/${cwId}/widget.qml`
            function save(): void {
                root._persistManifest(this);
            }
        }
    }

    Process {
        id: scanProc
        command: ["sh", "-c", `d="${root.dir}"; mkdir -p "$d"; printf '['; first=1; for m in "$d"/*/manifest.json; do [ -f "$m" ] || continue; if [ "$first" -eq 0 ]; then printf ','; fi; first=0; cat "$m"; done; printf ']'`]
        stdout: StdioCollector {
            onStreamFinished: {
                try {
                    root._rebuild(JSON.parse(text));
                } catch (e) {
                    console.warn("CustomWidgets: failed to parse manifests:", e);
                    root._rebuild([]);
                }
            }
        }
    }

    // Used for create/update/remove (file structure changes) → rescan afterwards.
    Process {
        id: opProc
        onExited: root.rescan()
    }
}
