#!/bin/bash

set -euo pipefail

ROOT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)

fail() {
  echo "FAIL: $1" >&2
  exit 1
}

assert_contains() {
  local path="$1"
  local pattern="$2"
  local message="$3"

  grep -Eq "$pattern" "$path" || fail "$message"
}

[[ -f $ROOT_DIR/config/hypr/hyprland-gui.conf ]] || \
  fail "Ryoku should ship HyprMod's managed config target"
[[ -f $ROOT_DIR/shell/modules/controlcenter/WindowTitle.qml ]] || \
  fail "missing control center title component"
assert_contains "$ROOT_DIR/config/hypr/hyprland.conf" \
  '^source = ~/\.config/hypr/hyprland-gui\.conf$' \
  "Ryoku Hyprland config should source HyprMod's managed config"
assert_contains "$ROOT_DIR/shell/modules/controlcenter/WindowTitle.qml" \
  'text: qsTr\("Advanced settings"\)' \
  "official settings should expose HyprMod as advanced settings"
assert_contains "$ROOT_DIR/shell/modules/controlcenter/WindowTitle.qml" \
  'Quickshell\.execDetached\(\["hyprmod"\]\)' \
  "advanced settings button should launch HyprMod"
assert_contains "$ROOT_DIR/shell/modules/controlcenter/WindowTitle.qml" \
  'QsWindow\.window\.destroy\(\)' \
  "advanced settings button should close the official settings window"
assert_contains "$ROOT_DIR/config/hypr/hyprland.conf" \
  '^windowrule = match:class \^\(io\.github\.bluemancz\.hyprmod\)\$, float true$' \
  "HyprMod should open as a floating advanced settings window"
assert_contains "$ROOT_DIR/config/hypr/hyprland.conf" \
  '^windowrule = match:class \^\(io\.github\.bluemancz\.hyprmod\)\$, center true$' \
  "HyprMod should open centered like Ryoku settings"
if grep -Fq 'text: qsTr("Ryoku Settings")' "$ROOT_DIR/shell/modules/controlcenter/WindowTitle.qml"; then
  fail "floating settings title should not duplicate the Ryoku Settings label"
fi

migration="$ROOT_DIR/migrations/1779515727.sh"
[[ -f $migration ]] || fail "missing HyprMod persistence migration"

tmp_dir=$(mktemp -d)
trap 'rm -rf "$tmp_dir"' EXIT

home_dir="$tmp_dir/home"
hypr_dir="$home_dir/.config/hypr"
hypr_conf="$hypr_dir/hyprland.conf"
hyprmod_conf="$hypr_dir/hyprland-gui.conf"
mkdir -p "$hypr_dir"

cat >"$hypr_conf" <<'HYPR'
source = ~/.config/hypr/colors.conf

general {
  gaps_in = 5
}
HYPR

cat >"$hyprmod_conf" <<'HYPRMOD'
# Generated by HyprMod
general:gaps_in = 2
HYPRMOD

env -u XDG_CONFIG_HOME HOME="$home_dir" RYOKU_PATH="$ROOT_DIR" bash "$migration" >/dev/null
env -u XDG_CONFIG_HOME HOME="$home_dir" RYOKU_PATH="$ROOT_DIR" bash "$migration" >/dev/null

source_count=$(grep -Fxc 'source = ~/.config/hypr/hyprland-gui.conf' "$hypr_conf")
(( source_count == 1 )) || fail "migration should add the HyprMod source exactly once"
float_count=$(grep -Fxc 'windowrule = match:class ^(io.github.bluemancz.hyprmod)$, float true' "$hypr_conf")
center_count=$(grep -Fxc 'windowrule = match:class ^(io.github.bluemancz.hyprmod)$, center true' "$hypr_conf")
(( float_count == 1 )) || fail "migration should add the HyprMod floating rule exactly once"
(( center_count == 1 )) || fail "migration should add the HyprMod center rule exactly once"
grep -Fxq 'general:gaps_in = 2' "$hyprmod_conf" || \
  fail "migration should preserve existing HyprMod-managed settings"

absolute_home="$tmp_dir/absolute-home"
absolute_hypr="$absolute_home/.config/hypr"
absolute_conf="$absolute_hypr/hyprland.conf"
mkdir -p "$absolute_hypr"
printf 'source = %s/.config/hypr/hyprland-gui.conf\n' "$absolute_home" >"$absolute_conf"

env -u XDG_CONFIG_HOME HOME="$absolute_home" RYOKU_PATH="$ROOT_DIR" bash "$migration" >/dev/null
absolute_count=$(grep -Ec 'hyprland-gui\.conf' "$absolute_conf")
(( absolute_count == 1 )) || fail "migration should detect HyprMod's existing absolute source path"

echo "PASS: HyprMod settings persist across Hyprland reloads"
