#!/bin/bash

set -euo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
UPSTREAM_NAME='i''NiR'
UPSTREAM_NAME_TITLE='I''nir'
UPSTREAM_NAME_LOWER='i''nir'
UPSTREAM_NAME_UPPER="${UPSTREAM_NAME_LOWER^^}"

fail() {
  echo "FAIL: $1" >&2
  exit 1
}

assert_no_match() {
  local path="$1"
  local pattern="$2"
  local message="$3"

  if rg -n "$pattern" "$ROOT_DIR/$path"; then
    fail "$message"
  fi
}

assert_match() {
  local path="$1"
  local pattern="$2"
  local message="$3"

  rg -n "$pattern" "$ROOT_DIR/$path" >/dev/null || fail "$message"
}

assert_no_match_except() {
  local path="$1"
  local pattern="$2"
  local exception="$3"
  local message="$4"
  local matches

  matches="$(rg -n "$pattern" "$ROOT_DIR/$path" || true)"
  matches="$(grep -vF "$exception" <<< "$matches" || true)"
  if [[ -n $matches ]]; then
    printf '%s\n' "$matches"
    fail "$message"
  fi
}

assert_no_path_glob() {
  local path="$1"
  local pattern="$2"
  local message="$3"
  local found

  found="$(find "$ROOT_DIR/$path" -name "$pattern" -print -quit)"
  [[ -z $found ]] || fail "$message: $found"
}

# Install and ISO output should be Ryoku-facing. Compatibility path cleanup may
# exist in migrations, but the live installer should not print or stage upstream branding.
assert_no_match "install" "${UPSTREAM_NAME}|snowarch|/${UPSTREAM_NAME_LOWER}|RYOKU_${UPSTREAM_NAME_UPPER}" \
  "install scripts should not expose upstream branding"
assert_no_match "iso" "${UPSTREAM_NAME}|snowarch|/root/${UPSTREAM_NAME_LOWER}|/${UPSTREAM_NAME_LOWER}|RYOKU_${UPSTREAM_NAME_UPPER}|ryoku-${UPSTREAM_NAME_LOWER}" \
  "ISO scripts should not expose upstream branding or paths"
assert_match "iso/builder/build-iso.sh" 'root/ryoku/shell|/ryoku-shell|ryoku-shell' \
  "ISO builder should use Ryoku shell naming"

# Runtime shell UI, translations, and install banner should not carry upstream
# product branding. Settings About pages are in-app credits surfaces and are
# intentionally allowed to mention upstream projects.
assert_no_match "shell/sdata/lib/tui.sh" "${UPSTREAM_NAME}|██╗██╗      ███╗   ██╗" \
  "shell setup banner should be Ryoku-branded"
assert_no_match "shell/welcome.qml" "${UPSTREAM_NAME}|${UPSTREAM_NAME_TITLE}|snowarch|scripts/${UPSTREAM_NAME_LOWER}|github\\.com/end-4" \
  "welcome screen should link and label Ryoku"
assert_no_match "shell/settings.qml" "${UPSTREAM_NAME}|${UPSTREAM_NAME_TITLE}|snowarch|github\\.com/end-4" \
  "settings window should label Ryoku"
assert_no_match "shell/modules/settings/ThemesConfig.qml" "${UPSTREAM_NAME}|${UPSTREAM_NAME_TITLE}" \
  "theme settings should expose Ryoku style naming"
assert_no_match "shell/modules/settings/SettingsOverlay.qml" "${UPSTREAM_NAME}|${UPSTREAM_NAME_TITLE}" \
  "settings search should expose Ryoku style naming"
assert_no_match "shell/modules/waffle/settings/pages/WThemesPage.qml" "${UPSTREAM_NAME}|${UPSTREAM_NAME_TITLE}" \
  "waffle theme settings should expose Ryoku style naming"
assert_no_match "shell/modules/waffle/settings/pages/WAboutPage.qml" "github\\.com/end-4" \
  "waffle about page should keep old upstream support links out of project actions"
assert_no_match_except "shell/translations" "${UPSTREAM_NAME}|Welcome to ${UPSTREAM_NAME_LOWER}|${UPSTREAM_NAME} Shell|${UPSTREAM_NAME} Update|${UPSTREAM_NAME_TITLE} TUI|Style: ${UPSTREAM_NAME}|Switch to ${UPSTREAM_NAME}|${UPSTREAM_NAME}-managed" "Ryoku's shell UI builds on ${UPSTREAM_NAME} by SnowArch." \
  "translations should not expose upstream branding"
assert_no_match "shell/dots/.config/vesktop/themes" "${UPSTREAM_NAME}|github\\.com/end-4/${UPSTREAM_NAME}|Runtime palette is generated by ${UPSTREAM_NAME}" \
  "Vesktop theme metadata should be Ryoku-branded"
assert_no_path_glob "shell/dots/.config/vesktop/themes" "*${UPSTREAM_NAME_LOWER}*" \
  "shipped Vesktop theme filenames should be Ryoku-branded"
assert_no_match "shell/dots/.config/matugen/templates" "Generated by ${UPSTREAM_NAME}|generated by ${UPSTREAM_NAME}" \
  "matugen templates should be Ryoku-branded"
assert_no_match "shell/defaults/matugen/templates" "Generated by ${UPSTREAM_NAME}|generated by ${UPSTREAM_NAME}|${UPSTREAM_NAME} Material" \
  "default matugen templates should be Ryoku-branded"
assert_no_match "shell/defaults/plugins" "${UPSTREAM_NAME}|${UPSTREAM_NAME_TITLE}|${UPSTREAM_NAME_LOWER}-sb-notification|${UPSTREAM_NAME_LOWER}Muted" \
  "default WebApp plugin scripts should be Ryoku-branded"
assert_no_match "shell/scripts/colors" "${UPSTREAM_NAME}|${UPSTREAM_NAME_TITLE}|github\\.com/end-4|snowarch" \
  "generated app theme metadata should be Ryoku-branded"
assert_no_match "shell/scripts/sddm/sync-pixel-sddm.py" "snowarch|github\\.com/end-4|${UPSTREAM_NAME}" \
  "generated SDDM metadata should use Ryoku links"
assert_no_match "shell/sdata/dist-arch" "${UPSTREAM_NAME} -|${UPSTREAM_NAME} desktop shell|github\\.com/snowarch/${UPSTREAM_NAME_LOWER}|registers ${UPSTREAM_NAME} dependencies|${UPSTREAM_NAME} deps|${UPSTREAM_NAME} dependencies" \
  "shell dependency package metadata should be Ryoku-branded"
assert_no_match "shell/sdata/dist-arch" "pkgname=${UPSTREAM_NAME_LOWER}-|dist-arch/${UPSTREAM_NAME_LOWER}-|Meta-package ${UPSTREAM_NAME_LOWER}" \
  "shell dependency package names should be Ryoku-branded"
assert_no_match "distro/arch/quickshell-ryoku" "${UPSTREAM_NAME} fix|${UPSTREAM_NAME}-patched|${UPSTREAM_NAME} shell|${UPSTREAM_NAME} project|${UPSTREAM_NAME} documents" \
  "quickshell package metadata should be Ryoku-branded"
assert_no_match "shell/.github" "${UPSTREAM_NAME}|${UPSTREAM_NAME_TITLE}|snowarch|github\\.com/end-4" \
  "GitHub templates should use Ryoku support links"

printf 'PASS: tests/ryoku-branding-scan.sh\n'
