#!/bin/bash

set -euo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"

fail() {
  echo "FAIL: $1" >&2
  exit 1
}

assert_no_match() {
  local path="$1"
  local pattern="$2"
  local message="$3"

  if rg -n "$pattern" "$ROOT_DIR/$path"; then
    fail "$message"
  fi
}

assert_match() {
  local path="$1"
  local pattern="$2"
  local message="$3"

  rg -n "$pattern" "$ROOT_DIR/$path" >/dev/null || fail "$message"
}

assert_no_path_glob() {
  local path="$1"
  local pattern="$2"
  local message="$3"
  local found

  found="$(find "$ROOT_DIR/$path" -name "$pattern" -print -quit)"
  [[ -z $found ]] || fail "$message: $found"
}

# Install and ISO output should be Ryoku-facing. Legacy path compatibility may
# exist in migrations, but the live installer should not print or stage iNiR.
assert_no_match "install" 'iNiR|snowarch|/inir|RYOKU_INIR' \
  "install scripts should not expose iNiR branding"
assert_no_match "iso" 'iNiR|snowarch|/root/inir|/inir|RYOKU_INIR|ryoku-inir' \
  "ISO scripts should not expose iNiR branding or paths"
assert_match "iso/builder/build-iso.sh" 'root/ryoku/shell|/ryoku-shell|ryoku-shell' \
  "ISO builder should use Ryoku shell naming"

# Runtime shell UI, translations, and install banner should not carry upstream
# product branding. About.qml is the in-app credits surface and is intentionally
# excluded.
assert_no_match "shell/sdata/lib/tui.sh" 'iNiR|██╗██╗      ███╗   ██╗' \
  "shell setup banner should be Ryoku-branded"
assert_no_match "shell/welcome.qml" 'iNiR|Inir|snowarch|scripts/inir|github\.com/end-4' \
  "welcome screen should link and label Ryoku, not iNiR"
assert_no_match "shell/settings.qml" 'iNiR|Inir|snowarch|github\.com/end-4' \
  "settings window should label Ryoku, not iNiR"
assert_no_match "shell/modules/settings/ThemesConfig.qml" 'iNiR|Inir' \
  "theme settings should expose Ryoku style naming"
assert_no_match "shell/modules/settings/SettingsOverlay.qml" 'iNiR|Inir' \
  "settings search should expose Ryoku style naming"
assert_no_match "shell/modules/waffle/settings/pages/WThemesPage.qml" 'iNiR|Inir' \
  "waffle theme settings should expose Ryoku style naming"
assert_no_match "shell/modules/waffle/settings/pages/WAboutPage.qml" 'snowarch|github\.com/end-4|iNiR' \
  "waffle about page should use Ryoku links; upstream credits live in About.qml and CREDITS.md"
assert_no_match "shell/translations" 'iNiR|Welcome to inir|iNiR Shell|iNiR Update|Inir TUI|Style: iNiR|Switch to iNiR|iNiR-managed' \
  "translations should not expose iNiR branding"
assert_no_match "shell/dots/.config/vesktop/themes" 'iNiR|github\.com/end-4/iNiR|Runtime palette is generated by iNiR' \
  "Vesktop theme metadata should be Ryoku-branded"
assert_no_path_glob "shell/dots/.config/vesktop/themes" '*inir*' \
  "shipped Vesktop theme filenames should be Ryoku-branded"
assert_no_match "shell/dots/.config/matugen/templates" 'Generated by iNiR|generated by iNiR' \
  "matugen templates should be Ryoku-branded"
assert_no_match "shell/defaults/matugen/templates" 'Generated by iNiR|generated by iNiR|iNiR Material' \
  "default matugen templates should be Ryoku-branded"
assert_no_match "shell/defaults/plugins" 'iNiR|Inir|inir-sb-notification|inirMuted' \
  "default WebApp plugin scripts should be Ryoku-branded"
assert_no_match "shell/scripts/colors" 'iNiR|Inir|github\.com/end-4|snowarch' \
  "generated app theme metadata should be Ryoku-branded"
assert_no_match "shell/scripts/sddm/sync-pixel-sddm.py" 'snowarch|github\.com/end-4|iNiR' \
  "generated SDDM metadata should use Ryoku links"
assert_no_match "shell/sdata/dist-arch" 'iNiR -|iNiR desktop shell|github\.com/snowarch/inir|registers iNiR dependencies|iNiR deps|iNiR dependencies' \
  "shell dependency package metadata should be Ryoku-branded"
assert_no_match "shell/sdata/dist-arch" 'pkgname=inir-|dist-arch/inir-|Meta-package inir' \
  "shell dependency package names should be Ryoku-branded"
assert_no_match "distro/arch/quickshell-ryoku" 'iNiR fix|iNiR-patched|iNiR shell|iNiR project|iNiR documents' \
  "quickshell package metadata should be Ryoku-branded"
assert_no_match "shell/.github" 'iNiR|Inir|snowarch|github\.com/end-4' \
  "GitHub templates should use Ryoku support links"

printf 'PASS: tests/ryoku-branding-scan.sh\n'
