accent = "#F25623"
cursor = "#CCD0CF"
foreground = "#CCD0CF"
background = "#171717"
selection_foreground = "#171717"
selection_background = "#F25623"

color0 = "#171717"
color1 = "#aeab94"
color2 = "#F25623"
color3 = "#4D4D4D"
color4 = "#88A57D"
color5 = "#F56E0F"
color6 = "#8A8A8A"
color7 = "#bcbfbc"
color8 = "#333333"
color9 = "#aeab94"
color10 = "#F25623"
color11 = "#4D4D4D"
color12 = "#88A57D"
color13 = "#F56E0F"
color14 = "#8A8A8A"
color15 = "#757d75"
