echo "Preserve HyprMod settings across Hyprland reloads"

hypr_dir="${XDG_CONFIG_HOME:-$HOME/.config}/hypr"
hypr_conf="$hypr_dir/hyprland.conf"
hyprmod_conf="$hypr_dir/hyprland-gui.conf"
hyprmod_source_line="source = ~/.config/hypr/hyprland-gui.conf"
hyprmod_float_rule="windowrule = match:class ^(io.github.bluemancz.hyprmod)$, float true"
hyprmod_center_rule="windowrule = match:class ^(io.github.bluemancz.hyprmod)$, center true"

has_hyprmod_source() {
  local conf="$1"
  local line value expanded

  [[ -f $conf ]] || return 1

  while IFS= read -r line; do
    [[ $line =~ ^[[:space:]]*source[[:space:]]*=[[:space:]]*(.+)$ ]] || continue
    value="${BASH_REMATCH[1]}"
    value="${value%%#*}"
    value="${value%"${value##*[![:space:]]}"}"
    expanded="${value/#\~/$HOME}"

    case "$expanded" in
      "$hyprmod_conf") return 0 ;;
    esac
  done <"$conf"

  return 1
}

mkdir -p "$hypr_dir"
if [[ ! -e $hyprmod_conf ]]; then
  printf '%s\n' "# Generated by HyprMod" >"$hyprmod_conf"
fi

if [[ -f $hypr_conf ]] && ! has_hyprmod_source "$hypr_conf"; then
  printf '\n# HyprMod managed settings\n%s\n' "$hyprmod_source_line" >>"$hypr_conf"
fi

if [[ -f $hypr_conf ]]; then
  grep -Fxq "$hyprmod_float_rule" "$hypr_conf" || printf '%s\n' "$hyprmod_float_rule" >>"$hypr_conf"
  grep -Fxq "$hyprmod_center_rule" "$hypr_conf" || printf '%s\n' "$hyprmod_center_rule" >>"$hypr_conf"
fi

if command -v hyprctl >/dev/null 2>&1; then
  hyprctl reload >/dev/null 2>&1 || true
fi
