echo "Switch the default app launcher to Vicinae (SUPER+Space)"

# Ryoku now ships Vicinae as the default app launcher in place of the in-frame
# ryoku-shell launcher. Converge existing installs: repoint the $menu keybind,
# autostart the Vicinae server from the Hyprland session, install the package,
# and deploy the unit + default config. Idempotent throughout.

hypr_conf="${XDG_CONFIG_HOME:-$HOME/.config}/hypr/hyprland.conf"

if [[ -f $hypr_conf ]]; then
  # Repoint the launcher keybind (SUPER+Space / SUPER+R both use $menu).
  sed -i "s|\$menu = sh -lc '\$HOME/.local/bin/ryoku-shell launcher'|\$menu = sh -lc 'vicinae toggle'|" "$hypr_conf"

  # Autostart the server and add the launcher's Hyprland integration once.
  if ! grep -q 'vicinae.service' "$hypr_conf"; then
    cat >>"$hypr_conf" <<'HYPR'

# Ryoku: Vicinae launcher (added by migration). Start the server for the
# session and frost its layer-shell surface; the $menu keybind toggles it.
exec-once = sh -lc 'systemctl --user reset-failed vicinae.service >/dev/null 2>&1 || true; systemctl --user start vicinae.service'
layerrule = match:namespace ^(vicinae)$, blur true
layerrule = match:namespace ^(vicinae)$, ignore_alpha 0.3
misc {
  focus_on_activate = true
}
HYPR
  fi
fi

# Install the launcher and its keychain backend. vicinae-bin does not pull
# qtkeychain-qt6, but the vicinae server hard-needs libqt6keychain.so.1, so add
# it explicitly (satisfied by the gnome-keyring secret service Ryoku ships).
ryoku-pkg-add qtkeychain-qt6 >/dev/null 2>&1 || true
if ryoku-cmd-missing vicinae; then
  ryoku-pkg-add vicinae-bin >/dev/null 2>&1 || ryoku-pkg-aur-add vicinae-bin >/dev/null 2>&1 || true
fi

# Deploy the systemd user unit so the autostart line above has something to run.
unit_src="$RYOKU_PATH/config/systemd/user/vicinae.service"
unit_dst="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user/vicinae.service"
if [[ -f $unit_src ]]; then
  mkdir -p "$(dirname "$unit_dst")"
  install -m 0644 "$unit_src" "$unit_dst"
  systemctl --user daemon-reload >/dev/null 2>&1 || true
fi

# Seed the default config only when the user has none, so in-app changes and
# any existing config survive re-runs.
settings_dst="${XDG_CONFIG_HOME:-$HOME/.config}/vicinae/settings.json"
if [[ ! -e $settings_dst && -f $RYOKU_PATH/config/vicinae/settings.json ]]; then
  mkdir -p "$(dirname "$settings_dst")"
  cp "$RYOKU_PATH/config/vicinae/settings.json" "$settings_dst"
fi

# Start it now if the launcher is installed and a user session is reachable;
# otherwise the Hyprland exec-once picks it up on the next login. The "ryoku"
# theme is generated by matugen on the next scheme apply (Vicinae falls back to
# its built-in palette until then).
if ryoku-cmd-present vicinae; then
  systemctl --user start vicinae.service >/dev/null 2>&1 || true
fi
