echo "Switch the default app launcher to Vicinae (SUPER+Space)"

# Ryoku now ships Vicinae as the default app launcher in place of the in-frame
# ryoku-shell launcher. Converge existing installs: repoint the $menu keybind,
# autostart the Vicinae server from the Hyprland session, install the package,
# and deploy the unit + default config. Idempotent throughout.

hypr_conf="${XDG_CONFIG_HOME:-$HOME/.config}/hypr/hyprland.conf"

if [[ -f $hypr_conf ]]; then
  # Point the launcher keybind at the runtime dispatcher, from either the
  # original quickshell launcher or an earlier direct `vicinae toggle`.
  sed -i \
    -e "s|\$menu = sh -lc '\$HOME/.local/bin/ryoku-shell launcher'|\$menu = sh -lc '\$HOME/.local/share/ryoku/bin/ryoku-launch-app'|" \
    -e "s|\$menu = sh -lc 'vicinae toggle'|\$menu = sh -lc '\$HOME/.local/share/ryoku/bin/ryoku-launch-app'|" \
    "$hypr_conf"

  # Convert an earlier unconditional vicinae autostart to the config-aware
  # dispatcher so Settings > Launcher controls whether the server runs. Use '#'
  # as the sed delimiter: the pattern contains '||', which would terminate an
  # 's|...|' expression early.
  sed -i "s#systemctl --user reset-failed vicinae.service >/dev/null 2>&1 || true; systemctl --user start vicinae.service#\$HOME/.local/share/ryoku/bin/ryoku-launch-app apply#" "$hypr_conf"

  # Add the launcher integration once: autostart (apply), layer frost, focus.
  if ! grep -qF 'ryoku-launch-app apply' "$hypr_conf"; then
    cat >>"$hypr_conf" <<'HYPR'

# Ryoku: app launcher backend (Settings > Launcher toggles Vicinae vs the
# built-in launcher). ryoku-launch-app apply starts/stops the Vicinae server to
# match; the $menu keybind dispatches to the selected launcher.
exec-once = sh -lc '$HOME/.local/share/ryoku/bin/ryoku-launch-app apply'
HYPR
  fi
  if ! grep -qF 'match:namespace ^(vicinae)$, blur true' "$hypr_conf"; then
    cat >>"$hypr_conf" <<'HYPR'
layerrule = match:namespace ^(vicinae)$, blur true
layerrule = match:namespace ^(vicinae)$, ignore_alpha 0.3
HYPR
  fi
  if ! grep -qF 'focus_on_activate' "$hypr_conf"; then
    cat >>"$hypr_conf" <<'HYPR'
misc {
  focus_on_activate = true
}
HYPR
  fi
fi

# Install the launcher and its keychain backend. vicinae-bin does not pull
# qtkeychain-qt6, but the vicinae server hard-needs libqt6keychain.so.1, so add
# it explicitly (satisfied by the gnome-keyring secret service Ryoku ships).
ryoku-pkg-add qtkeychain-qt6 >/dev/null 2>&1 || true
if ryoku-cmd-missing vicinae; then
  ryoku-pkg-add vicinae-bin >/dev/null 2>&1 || ryoku-pkg-aur-add vicinae-bin >/dev/null 2>&1 || true
fi

# Deploy the systemd user unit so the autostart line above has something to run.
unit_src="$RYOKU_PATH/config/systemd/user/vicinae.service"
unit_dst="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user/vicinae.service"
if [[ -f $unit_src ]]; then
  mkdir -p "$(dirname "$unit_dst")"
  install -m 0644 "$unit_src" "$unit_dst"
  systemctl --user daemon-reload >/dev/null 2>&1 || true
fi

# Seed the default config only when the user has none, so in-app changes and
# any existing config survive re-runs.
settings_dst="${XDG_CONFIG_HOME:-$HOME/.config}/vicinae/settings.json"
if [[ ! -e $settings_dst && -f $RYOKU_PATH/config/vicinae/settings.json ]]; then
  mkdir -p "$(dirname "$settings_dst")"
  cp "$RYOKU_PATH/config/vicinae/settings.json" "$settings_dst"
fi

# Reconcile the launcher server with the configured backend now if a user
# session is reachable; otherwise the Hyprland exec-once picks it up on the next
# login. Defaults to Vicinae (Settings > Launcher can turn it off). The "ryoku"
# theme is generated by matugen on the next scheme apply (Vicinae falls back to
# its built-in palette until then).
if command -v ryoku-launch-app >/dev/null 2>&1; then
  ryoku-launch-app apply >/dev/null 2>&1 || true
fi
