import QtQuick
import QtQuick.Controls
import QtQuick.Layouts
import Quickshell
import Quickshell.Io
import Ryoku.Config
import qs.settingsgui.Commons
import qs.settingsgui.Services.System
import qs.settingsgui.Services.Theming
import qs.settingsgui.Services.UI
import qs.settingsgui.Widgets
import qs.services

ColumnLayout {
  id: root
  spacing: Style.marginL
  Layout.fillWidth: true

  property var timeOptions
  property var schemeColorsCache: ({})
  property int cacheVersion: 0
  property var screen

  signal openDownloadPopup

  // RYOKU: scan installed/downloaded color schemes when the tab opens so they
  // persist across shell reloads. ColorSchemeService otherwise only scanned
  // after a download/delete, so downloaded schemes vanished from the picker on
  // restart (and the downloader re-offered them).
  Component.onCompleted: ColorSchemeService.loadColorSchemes()

  // RYOKU: the installed ryoku themes (themes/<name>) drive the scheme picker.
  // Each applies via `ryoku-theme-set <name>` which writes the live scheme.json.
  property var ryokuThemes: []
  Process {
    id: themeListProc
    command: ["ryoku-theme-list", "--jsonl"]
    running: true
    stdout: StdioCollector {
      onStreamFinished: {
        const out = [];
        const lines = text.trim().split("\n");
        for (let i = 0; i < lines.length; i++) {
          const l = lines[i].trim();
          if (!l)
            continue;
          try {
            out.push(JSON.parse(l));
          } catch (e) {}
        }
        root.ryokuThemes = out;
      }
    }
  }

  // RYOKU: catalog of repo themes (remote index.json, local install fallback) so
  // themes you don't have yet can be downloaded. Catalog generated by ryoku-theme-index.
  property var catalogThemes: []
  property string downloadingName: ""
  readonly property var downloadable: {
    const installed = ({});
    for (let i = 0; i < root.ryokuThemes.length; i++)
      installed[root.ryokuThemes[i].name] = true;
    return root.catalogThemes.filter(function (c) {
      return c && c.name && !installed[c.name];
    });
  }

  function normalizeSchemeName(name) {
    return String(name || "").toLowerCase().replace(/[^a-z0-9]+/g, "");
  }

  // RYOKU: installed color schemes (ColorSchemeService = downloaded from
  // ryoku-extras + preinstalled) surfaced as selectable picker tiles. Deduped
  // against the ryoku themes above by normalized name so nothing shows twice.
  readonly property var colorSchemeTiles: {
    const themeNames = ({});
    for (let i = 0; i < root.ryokuThemes.length; i++)
      themeNames[root.normalizeSchemeName(root.ryokuThemes[i].name)] = true;
    const out = [];
    for (let j = 0; j < ColorSchemeService.schemes.length; j++) {
      const nm = root.extractSchemeName(ColorSchemeService.schemes[j]);
      if (!nm || nm === "Ryoku (default)")
        continue;
      if (!themeNames[root.normalizeSchemeName(nm)])
        out.push({
                   "name": nm
                 });
    }
    return out;
  }
  Process {
    id: catalogProc
    command: ["sh", "-c", "curl -fsSL \"https://raw.githubusercontent.com/neur0map/ryoku-arch/${RYOKU_THEMES_BRANCH:-main}/themes/index.json\" 2>/dev/null || cat \"$HOME/.local/share/ryoku/themes/index.json\" 2>/dev/null || true"]
    running: true
    stdout: StdioCollector {
      onStreamFinished: {
        try {
          const d = JSON.parse(text);
          root.catalogThemes = (d && d.themes) ? d.themes : [];
        } catch (e) {
          root.catalogThemes = [];
        }
      }
    }
  }
  Process {
    id: downloadProc
    property string themeName: ""
    command: ["ryoku-theme-download", downloadProc.themeName]
    onExited: {
      root.downloadingName = "";
      themeListProc.running = true; // refresh installed list → moves it to a tile
    }
  }
  function downloadTheme(name) {
    if (root.downloadingName !== "")
      return;
    root.downloadingName = name;
    downloadProc.themeName = name;
    downloadProc.running = true;
  }

  function extractSchemeName(schemePath) {
    var pathParts = schemePath.split("/");
    var filename = pathParts[pathParts.length - 1];
    var schemeName = filename.replace(".json", "");

    if (schemeName === "ryoku-default") {
      schemeName = "Ryoku (default)";
    } else if (schemeName === "ryoku-legacy") {
      schemeName = "Ryoku (legacy)";
    } else if (schemeName === "Tokyo-Night") {
      schemeName = "Tokyo Night";
    } else if (schemeName === "Rosepine") {
      schemeName = "Rose Pine";
    }

    return schemeName;
  }

  function getSchemeColor(schemeName, colorKey) {
    var _ = cacheVersion;

    if (schemeColorsCache[schemeName]) {
      var entry = schemeColorsCache[schemeName];
      var variant = entry;

      if (entry.dark || entry.light) {
        // RYOKU WIRED: use Colours.light to determine dark/light variant
        variant = (!Colours.light) ? (entry.dark || entry.light) : (entry.light || entry.dark);
      }

      if (variant && variant[colorKey]) {
        return variant[colorKey];
      }
    }

    if (colorKey === "mSurface")
      return Color.mSurfaceVariant;
    if (colorKey === "mPrimary")
      return Color.mPrimary;
    if (colorKey === "mSecondary")
      return Color.mSecondary;
    if (colorKey === "mTertiary")
      return Color.mTertiary;
    if (colorKey === "mError")
      return Color.mError;
    return Color.mOnSurfaceVariant;
  }

  function schemeLoaded(schemeName, jsonData) {
    var value = jsonData || {};
    schemeColorsCache[schemeName] = value;
    cacheVersion++;
  }

  Connections {
    target: ColorSchemeService
    function onSchemesChanged() {
      root.schemeColorsCache = {};
      root.cacheVersion++;
    }
  }

  Item {
    id: fileLoaders
    visible: false

    Repeater {
      model: ColorSchemeService.schemes
      delegate: Item {
        FileView {
          path: modelData
          blockLoading: false
          onLoaded: {
            var schemeName = root.extractSchemeName(path);

            try {
              var jsonData = JSON.parse(text());
              root.schemeLoaded(schemeName, jsonData);
            } catch (e) {
              Logger.w("ColorSchemeTab", "Failed to parse JSON for scheme:", schemeName, e);
              root.schemeLoaded(schemeName, null);
            }
          }
        }
      }
    }
  }

  NToggle {
    // RYOKU WIRED: Colours.light reflects dark/light; Colours.setMode() → ryoku scheme set -m.
    // Disabled while a custom theme is active (themes define their own mode; toggling
    // would have no effect since the theme is re-derived in its native mode).
    label: I18n.tr("tooltips.switch-to-dark-mode")
    description: Colours.flavour === "custom" ? "This theme sets its own mode — choose a light or dark theme below to switch." : I18n.tr("panels.color-scheme.dark-mode-switch-description")
    checked: !Colours.light
    enabled: Colours.flavour !== "custom"
    opacity: enabled ? 1.0 : 0.6
    onToggled: checked => {
                 const mode = checked ? "dark" : "light";
                 Colours.setMode(mode);
                 // RYOKU: when "Sync system theme" is on, mirror the live light/dark flip
                 // to GNOME/GTK immediately. Passes the new mode explicitly so it doesn't
                 // depend on the per-theme marker. Mirrors the upstream onDarkModeChanged push.
                 if (GlobalConfig.services.syncSystemTheme)
                   Quickshell.execDetached(["ryoku-theme-set-gnome", mode]);
                 root.cacheVersion++;
               }
  }

  NToggle {
    // RYOKU WIRED: GlobalConfig.services.syncSystemTheme gates the GNOME/GTK sync
    // (ryoku-theme-set-gnome) in the ryoku-theme-set pipeline. Toggling on mirrors
    // the system toolkit theme to the current light/dark variant immediately.
    label: I18n.tr("panels.color-scheme.sync-gsettings-label")
    description: I18n.tr("panels.color-scheme.sync-gsettings-description")
    checked: GlobalConfig.services.syncSystemTheme
    onToggled: checked => {
                 GlobalConfig.services.syncSystemTheme = checked;
                 GlobalConfig.save();
                 if (checked)
                   Quickshell.execDetached(["ryoku-theme-set-gnome", Colours.light ? "light" : "dark"]);
               }
  }

  NComboBox {
    // TODO: wire to ryoku dark mode scheduler (no scheduler in ryoku yet)
    label: I18n.tr("panels.color-scheme.dark-mode-mode-label")
    description: I18n.tr("panels.color-scheme.dark-mode-mode-description")
    enabled: false
    opacity: 0.45

    model: [
      {
        "name": I18n.tr("panels.color-scheme.dark-mode-mode-off"),
        "key": "off"
      },
      {
        "name": I18n.tr("panels.color-scheme.dark-mode-mode-manual"),
        "key": "manual"
      },
      {
        "name": I18n.tr("common.location"),
        "key": "location"
      }
    ]

    currentKey: "off"
  }

  ColumnLayout {
    // TODO: wire to ryoku dark mode scheduler (no scheduler in ryoku yet)
    spacing: Style.marginS
    visible: false
    enabled: false
    opacity: 0.45

    NLabel {
      label: I18n.tr("panels.display.night-light-manual-schedule-label")
      description: I18n.tr("panels.display.night-light-manual-schedule-description")
    }

    RowLayout {
      Layout.fillWidth: false
      spacing: Style.marginS

      NText {
        text: I18n.tr("panels.display.night-light-manual-schedule-sunrise")
        pointSize: Style.fontSizeM
        color: Color.mOnSurfaceVariant
      }

      NComboBox {
        model: root.timeOptions
        currentKey: ""
        placeholder: I18n.tr("panels.display.night-light-manual-schedule-select-start")
        minimumWidth: 120
      }

      Item {
        Layout.preferredWidth: 20
      }

      NText {
        text: I18n.tr("panels.display.night-light-manual-schedule-sunset")
        pointSize: Style.fontSizeM
        color: Color.mOnSurfaceVariant
      }

      NComboBox {
        model: root.timeOptions
        currentKey: ""
        placeholder: I18n.tr("panels.display.night-light-manual-schedule-select-stop")
        minimumWidth: 120
      }
    }
  }

  NDivider {
    Layout.fillWidth: true
  }

  NToggle {
    // RYOKU WIRED: GlobalConfig.services.smartScheme (serviceconfig.hpp:31) — enables wallpaper-derived colour scheme
    label: I18n.tr("panels.color-scheme.color-source-use-wallpaper-colors-label")
    description: I18n.tr("panels.color-scheme.color-source-use-wallpaper-colors-description")
    checked: GlobalConfig.services.smartScheme
    onToggled: checked => {
                 GlobalConfig.services.smartScheme = checked;
                 GlobalConfig.save();
                 // RYOKU: turning it on immediately derives the scheme from the
                 // current wallpaper (live, no restart). Off leaves the current
                 // scheme so the predefined theme tiles below take over.
                 if (checked)
                   Quickshell.execDetached(["ryoku", "scheme", "from-wallpaper"]);
               }
  }

  NComboBox {
    // TODO: wire to ryoku per-monitor colour source (no per-monitor config in ryoku yet)
    Layout.fillWidth: true
    label: I18n.tr("panels.color-scheme.wallpaper-monitor-source-label")
    description: I18n.tr("panels.color-scheme.wallpaper-monitor-source-description")
    enabled: false
    opacity: 0.45
    model: []
    currentKey: ""
  }

  NComboBox {
    // TODO: wire to ryoku generation method (no generationMethod config exposed in ryoku yet)
    Layout.fillWidth: true
    label: I18n.tr("panels.color-scheme.wallpaper-method-label")
    description: I18n.tr("panels.color-scheme.wallpaper-method-description")
    enabled: false
    opacity: 0.45
    model: []
    currentKey: ""
  }

  NBox {
    // RYOKU WIRED: visible when GlobalConfig.services.smartScheme is true
    visible: GlobalConfig.services.smartScheme
    Layout.fillWidth: true
    implicitHeight: descriptionColumn.implicitHeight + Style.margin2L
    color: Color.mSurface

    Column {
      id: descriptionColumn
      anchors.left: parent.left
      anchors.right: parent.right
      anchors.top: parent.top
      anchors.margins: Style.marginL
      spacing: Style.marginM

      NText {
        width: parent.width
        wrapMode: Text.WordWrap
        text: I18n.tr("panels.color-scheme.color-source-use-wallpaper-colors-description")
        pointSize: Style.fontSizeS
        color: Color.mOnSurfaceVariant
      }

      Row {
        id: colorPreviewRow
        spacing: Style.marginS

        property int diameter: 16 * Style.uiScaleRatio

        Repeater {
          model: [Color.mPrimary, Color.mSecondary, Color.mTertiary, Color.mSurface]

          Rectangle {
            width: colorPreviewRow.diameter
            height: colorPreviewRow.diameter
            radius: width * 0.5
            color: modelData
          }
        }
      }
    }
  }

  NDivider {
    Layout.fillWidth: true
  }

  ColumnLayout {
    // RYOKU WIRED: enabled when smartScheme (wallpaper colors) is off
    spacing: Style.marginM
    Layout.fillWidth: true
    enabled: !GlobalConfig.services.smartScheme

    NHeader {
      label: I18n.tr("panels.color-scheme.predefined-title")
      description: I18n.tr("panels.color-scheme.predefined-desc")
      Layout.fillWidth: true
    }

    GridLayout {
      columns: 2
      rowSpacing: Style.marginM
      columnSpacing: Style.marginM
      Layout.fillWidth: true

      Repeater {
        model: root.ryokuThemes

        Rectangle {
          id: schemeItem

          required property var modelData
          readonly property string themeName: modelData.name
          readonly property string themeDisplay: modelData.display

          // preview colors read live from the theme's own colors.toml
          property color cBg: Color.mSurface
          property color cText: Color.mOnSurface
          property color cAccent: Color.mPrimary
          property color cSecondary: Color.mSecondary
          property color cTertiary: Color.mTertiary

          FileView {
            path: schemeItem.modelData.path + "/colors.toml"
            onLoaded: {
              const t = text();
              const grab = function (key, fb) {
                const m = t.match(new RegExp(key + '\\s*=\\s*"?(#[0-9A-Fa-f]{6})'));
                return m ? m[1] : fb;
              };
              schemeItem.cBg = grab("background", "#222222");
              schemeItem.cText = grab("foreground", "#CCCCCC");
              schemeItem.cAccent = grab("accent", grab("color4", "#888888"));
              schemeItem.cSecondary = grab("color6", schemeItem.cAccent);
              schemeItem.cTertiary = grab("color5", schemeItem.cAccent);
            }
          }

          opacity: enabled ? 1.0 : 0.6
          Layout.fillWidth: true
          Layout.alignment: Qt.AlignHCenter
          height: 50 * Style.uiScaleRatio
          radius: Style.radiusS
          color: schemeItem.cBg
          border.width: Style.borderL
          border.color: {
            if ((Colours.scheme === schemeItem.themeName) && schemeItem.enabled)
              return Color.mSecondary;
            if (itemMouseArea.containsMouse)
              return Color.mHover;
            return Color.mOutline;
          }

          RowLayout {
            id: scheme
            anchors.fill: parent
            anchors.margins: Style.marginL
            spacing: Style.marginS

            NText {
              text: schemeItem.themeDisplay
              pointSize: Style.fontSizeS
              color: schemeItem.cText
              Layout.fillWidth: true
              elide: Text.ElideRight
              verticalAlignment: Text.AlignVCenter
              maximumLineCount: 1
            }

            property int diameter: 16 * Style.uiScaleRatio

            Rectangle {
              width: scheme.diameter
              height: scheme.diameter
              radius: scheme.diameter * 0.5
              color: schemeItem.cAccent
              border.width: Style.borderS
              border.color: Qt.alpha(schemeItem.cText, 0.3)
            }

            Rectangle {
              width: scheme.diameter
              height: scheme.diameter
              radius: scheme.diameter * 0.5
              color: schemeItem.cSecondary
              border.width: Style.borderS
              border.color: Qt.alpha(schemeItem.cText, 0.3)
            }

            Rectangle {
              width: scheme.diameter
              height: scheme.diameter
              radius: scheme.diameter * 0.5
              color: schemeItem.cTertiary
              border.width: Style.borderS
              border.color: Qt.alpha(schemeItem.cText, 0.3)
            }
          }

          MouseArea {
            // RYOKU: disable wallpaper colors + apply the theme (writes live scheme.json + restarts)
            id: itemMouseArea
            anchors.fill: parent
            enabled: schemeItem.enabled
            hoverEnabled: true
            cursorShape: Qt.PointingHandCursor
            onClicked: {
              GlobalConfig.services.smartScheme = false;
              GlobalConfig.save();
              Quickshell.execDetached(["ryoku-theme-set", schemeItem.themeName]);
            }
          }

          Rectangle {
            visible: (Colours.scheme === schemeItem.themeName) && schemeItem.enabled
            anchors.right: parent.right
            anchors.top: parent.top
            anchors.topMargin: -3
            width: 20
            height: 20
            radius: Math.min(Style.radiusL, width / 2)
            color: Color.mSecondary
            border.width: Style.borderS
            border.color: Color.mOnSecondary

            NIcon {
              icon: "check"
              pointSize: Style.fontSizeXS
              color: Color.mOnSecondary
              anchors.centerIn: parent
            }
          }

          Behavior on border.color {
            ColorAnimation {
              duration: Style.animationNormal
            }
          }
        }
      }
    }

    // RYOKU: repo themes not installed yet — click to fetch into ~/.config/ryoku/themes.
    NText {
      visible: root.downloadable.length > 0
      Layout.fillWidth: true
      Layout.topMargin: Style.marginM
      text: root.downloadable.length + " more theme(s) available to download"
      pointSize: Style.fontSizeS
      color: Color.mOnSurfaceVariant
    }

    GridLayout {
      visible: root.downloadable.length > 0
      Layout.fillWidth: true
      columns: 2
      rowSpacing: Style.marginM
      columnSpacing: Style.marginM

      Repeater {
        model: root.downloadable

        Rectangle {
          id: dlItem

          required property var modelData
          readonly property bool busy: root.downloadingName === dlItem.modelData.name

          opacity: (root.downloadingName !== "" && !dlItem.busy) ? 0.5 : 1.0
          Layout.fillWidth: true
          height: 50 * Style.uiScaleRatio
          radius: Style.radiusS
          color: dlItem.modelData.background || Color.mSurface
          border.width: Style.borderL
          border.color: dlMouse.containsMouse ? Color.mHover : Color.mOutline

          RowLayout {
            anchors.fill: parent
            anchors.margins: Style.marginL
            spacing: Style.marginS

            NText {
              text: dlItem.modelData.display
              pointSize: Style.fontSizeS
              color: dlItem.modelData.foreground || Color.mOnSurface
              Layout.fillWidth: true
              elide: Text.ElideRight
              verticalAlignment: Text.AlignVCenter
              maximumLineCount: 1
            }

            Repeater {
              model: [dlItem.modelData.accent, dlItem.modelData.secondary, dlItem.modelData.tertiary]

              delegate: Rectangle {
                required property var modelData
                width: 16 * Style.uiScaleRatio
                height: width
                radius: width * 0.5
                color: modelData || "#888888"
                border.width: Style.borderS
                border.color: Qt.alpha(dlItem.modelData.foreground || "#cccccc", 0.3)
              }
            }

            NIcon {
              icon: dlItem.busy ? "refresh" : "download"
              pointSize: Style.fontSizeM
              color: dlItem.modelData.foreground || Color.mOnSurface
            }
          }

          MouseArea {
            id: dlMouse
            anchors.fill: parent
            enabled: !dlItem.busy && root.downloadingName === ""
            hoverEnabled: true
            cursorShape: Qt.PointingHandCursor
            onClicked: root.downloadTheme(dlItem.modelData.name)
          }
        }
      }
    }

    // RYOKU: installed color schemes (downloaded from ryoku-extras + preinstalled),
    // selectable like the themes above. Apply via ColorSchemeService (writes the
    // live colors.json). Deduped against the themes so names never appear twice.
    NText {
      visible: root.colorSchemeTiles.length > 0
      Layout.fillWidth: true
      Layout.topMargin: Style.marginM
      text: qsTr("Color schemes")
      pointSize: Style.fontSizeM
      font.weight: Style.fontWeightBold
      color: Color.mOnSurface
    }

    GridLayout {
      visible: root.colorSchemeTiles.length > 0
      Layout.fillWidth: true
      columns: 2
      rowSpacing: Style.marginM
      columnSpacing: Style.marginM

      Repeater {
        model: root.colorSchemeTiles

        Rectangle {
          id: csItem

          required property var modelData
          readonly property string schemeName: modelData.name
          readonly property bool active: Colours.scheme === csItem.schemeName

          property color cBg: root.getSchemeColor(csItem.schemeName, "mSurface")
          property color cText: root.getSchemeColor(csItem.schemeName, "mOnSurface")
          property color cAccent: root.getSchemeColor(csItem.schemeName, "mPrimary")
          property color cSecondary: root.getSchemeColor(csItem.schemeName, "mSecondary")
          property color cTertiary: root.getSchemeColor(csItem.schemeName, "mTertiary")

          opacity: enabled ? 1.0 : 0.6
          Layout.fillWidth: true
          Layout.alignment: Qt.AlignHCenter
          height: 50 * Style.uiScaleRatio
          radius: Style.radiusS
          color: csItem.cBg
          border.width: Style.borderL
          border.color: {
            if (csItem.active && csItem.enabled)
              return Color.mSecondary;
            if (csMouse.containsMouse)
              return Color.mHover;
            return Color.mOutline;
          }

          RowLayout {
            id: csRow
            anchors.fill: parent
            anchors.margins: Style.marginL
            spacing: Style.marginS

            property int diameter: 16 * Style.uiScaleRatio

            NText {
              text: csItem.schemeName
              pointSize: Style.fontSizeS
              color: csItem.cText
              Layout.fillWidth: true
              elide: Text.ElideRight
              verticalAlignment: Text.AlignVCenter
              maximumLineCount: 1
            }

            Repeater {
              model: [csItem.cAccent, csItem.cSecondary, csItem.cTertiary]
              delegate: Rectangle {
                required property var modelData
                width: csRow.diameter
                height: csRow.diameter
                radius: csRow.diameter * 0.5
                color: modelData
                border.width: Style.borderS
                border.color: Qt.alpha(csItem.cText, 0.3)
              }
            }
          }

          MouseArea {
            id: csMouse
            anchors.fill: parent
            enabled: csItem.enabled
            hoverEnabled: true
            cursorShape: Qt.PointingHandCursor
            onClicked: {
              GlobalConfig.services.smartScheme = false;
              GlobalConfig.save();
              Quickshell.execDetached(["ryoku-scheme-set", csItem.schemeName]);
            }
          }

          Rectangle {
            visible: csItem.active
            anchors.right: parent.right
            anchors.top: parent.top
            anchors.topMargin: -3
            width: 20
            height: 20
            radius: Math.min(Style.radiusL, width / 2)
            color: Color.mSecondary
            border.width: Style.borderS
            border.color: Color.mOnSecondary

            NIcon {
              icon: "check"
              pointSize: Style.fontSizeXS
              color: Color.mOnSecondary
              anchors.centerIn: parent
            }
          }

          Behavior on border.color {
            ColorAnimation {
              duration: Style.animationNormal
            }
          }
        }
      }
    }

    // RYOKU: browse + download color schemes from the ryoku-extras catalogue
    // (opens SchemeDownloader, which has its own refresh-from-repo button).
    NButton {
      Layout.topMargin: Style.marginM
      text: I18n.tr("panels.color-scheme.download-title")
      icon: "download"
      outlined: true
      onClicked: root.openDownloadPopup()
    }
  }
}
