ryoku_profile_setup() {
  local target_user target_home target_uid
  local mpd_conf mpd_state_dir rmpc_conf_dir rmpc_conf
  local sock

  target_user="$(ryoku_profile_target_user)"
  target_home="$(ryoku_profile_target_home)"
  target_uid="$(ryoku_profile_target_uid)"

  [[ -n $target_user && -n $target_home && $target_user != "root" ]] || {
    printf 'Error: could not resolve target user for music setup.\n' >&2
    return 1
  }

  # ── MPD config (user-mode) ─────────────────────────────────────────
  mpd_conf="$target_home/.config/mpd/mpd.conf"
  mpd_state_dir="$target_home/.local/state/mpd"

  install -d -m 0755 -o "$target_uid" -g "$target_uid" \
    "$target_home/.config/mpd" \
    "$mpd_state_dir" \
    "$mpd_state_dir/playlists"

  if [[ ! -f $mpd_conf ]]; then
    cat <<MPD_EOF >"$mpd_conf"
# Generated by ryoku music-rmpc profile. Safe to edit; ryoku will not
# overwrite this file on subsequent installs. The Settings → Services →
# Music panel writes music_directory in place via a targeted sed.

music_directory     "$target_home/Music"
playlist_directory  "$mpd_state_dir/playlists"
db_file             "$mpd_state_dir/database"
log_file            "syslog"
pid_file            "$mpd_state_dir/pid"
state_file          "$mpd_state_dir/state"
sticker_file        "$mpd_state_dir/sticker.sql"

auto_update         "yes"
auto_update_depth   "0"

bind_to_address     "$XDG_RUNTIME_DIR/mpd.socket"
restore_paused      "yes"

input {
    plugin "curl"
}

audio_output {
    type        "pipewire"
    name        "PipeWire Sound Server"
}

audio_output {
    type        "fifo"
    name        "FIFO (cava visualizer)"
    path        "/tmp/mpd.fifo"
    format      "44100:16:2"
}

# MPRIS bridge: lets the in-shell media widget surface MPD tracks.
audio_output {
    type        "alsa"
    name        "ALSA dummy"
    device      "null"
    mixer_type  "none"
    enabled     "no"
}
MPD_EOF
    chown "$target_uid:$target_uid" "$mpd_conf"
  fi

  # Ensure the music dir exists so first launch doesn't crash on scan.
  install -d -m 0755 -o "$target_uid" -g "$target_uid" "$target_home/Music"

  # ── rmpc config (user-mode) ────────────────────────────────────────
  rmpc_conf_dir="$target_home/.config/rmpc"
  rmpc_conf="$rmpc_conf_dir/config.ron"

  install -d -m 0755 -o "$target_uid" -g "$target_uid" \
    "$rmpc_conf_dir" \
    "$rmpc_conf_dir/themes"

  if [[ ! -f $rmpc_conf ]]; then
    sock="$(sudo -u "$target_user" sh -c 'echo "$XDG_RUNTIME_DIR/mpd.socket"' 2>/dev/null)"
    [[ -n $sock ]] || sock="/run/user/$target_uid/mpd.socket"
    cat <<RMPC_EOF >"$rmpc_conf"
// Generated by ryoku music-rmpc profile. The theme line is rewritten
// every time matugen runs (see shell/scripts/colors/modules/95-rmpc.sh).
(
    address: "$sock",
    password: None,
    theme: Some("ryoku"),
    cache_dir: None,
    on_song_change: None,
    volume_step: 5,
    scrolloff: 0,
    wrap_navigation: false,
    enable_mouse: true,
    enable_config_hot_reload: true,
    status_update_interval_ms: 1000,
)
RMPC_EOF
    chown "$target_uid:$target_uid" "$rmpc_conf"
  fi

  # ── Refresh systemd user units so mpd.service/socket and mpd-mpris ──
  # become visible. Intentionally do NOT enable or start anything here.
  # The daemon (and the MPRIS bridge that surfaces MPD in the in-shell
  # media widget / bar / sidebar) stays off until the user explicitly
  # toggles "Enable music daemon" under Settings, Compositor, Music
  # Player, which invokes bin/ryoku-music-daemon-set on.
  if command -v systemctl >/dev/null 2>&1; then
    sudo -u "$target_user" systemctl --user daemon-reload >/dev/null 2>&1 || true
  fi

  # ── Trigger a matugen colour pass so the rmpc theme appears. ───────
  if [[ -x "${RYOKU_PATH:-$target_home/.local/share/ryoku}/bin/ryoku-theme-set" ]]; then
    sudo -u "$target_user" env HOME="$target_home" \
      "${RYOKU_PATH:-$target_home/.local/share/ryoku}/bin/ryoku-theme-set" --reapply >/dev/null 2>&1 || true
  fi

  printf '[music-rmpc] Installed. The mpd daemon is OFF by default.\n'
  printf '[music-rmpc] Open Settings, Services, Music Player to enable the daemon and pick your library folder.\n'
}
