blank_issues_enabled: false
contact_links:
  - name: Suggestion
    url: https://github.com/neur0map/ryoku-arch/discussions
    about: Suggest a new feature, change to existing feature, or other ideas in Discussions.
