-- managed by ryoku-gpu. empty by default = hyprland picks its own GPU.
--
-- multi-GPU box (discrete radeon/geforce next to the iGPU): `ryoku-gpu persist`
-- rewrites this file with an `hl.env("AQ_DRM_DEVICES", ...)` call pinning the
-- strongest GPU as the primary renderer. back to hyprland's default selection:
-- `ryoku-gpu disable`.
--
-- takes effect on the next hyprland login (env is read at start).
