require("modules.env")
require("keyboard")
-- Hardware drop-ins, generated at runtime: ryoku-gpu writes gpu.lua, ryoku-monitor
-- writes monitors.lua, and both are rewritten on a hotplug or a GPU reset. Load
-- them with pcall so a half-written or corrupt one falls back to Hyprland's
-- defaults instead of taking the whole config into emergency mode; ryoku doctor
-- repairs the file and autoscale regenerates it on the next login.
pcall(require, "gpu")
pcall(require, "monitors")
-- Manual monitor overrides: ~/.config/hypr/monitors_user.lua is hand-written and
-- never shipped or touched by ryoku-monitor. Loaded after the generated
-- monitors.lua so a hand-set panel (a fake-EDID display that needs a forced mode
-- or modeline, or a pinned layout) wins. See monitors_user.lua.example.
pcall(require, "monitors_user")
require("modules.displays")
require("modules.input")
require("modules.decoration")
require("modules.animations")
require("modules.binds")
require("modules.resize")
require("modules.ryoshot")
require("modules.window_rules")
require("modules.fullscreen")
require("modules.autostart")

-- Active theme (Ryoku Settings): the selected theme's real Lua (motion design and
-- decoration nuances), loaded after the base modules and before settings.lua so a
-- Look-tab tweak still wins over the theme.
pcall(require, "theme")

-- Ryoku Settings: machine-state generated by the hub (ryoku-hub), never shipped.
-- Loads after the base modules so the GUI's tweaks override the shipped defaults,
-- and before user.lua so a hand-written user file still wins.
pcall(require, "settings")

pcall(require, "modules.private")

-- GhostType hotkey (managed by the app)
pcall(require, "ghosttype")

-- User overrides: ~/.config/hypr/user.lua is never shipped or touched by updates
-- and loads last, so your settings win over the base config.
pcall(require, "user")
