require("modules.env")
require("keyboard")
require("gpu")
require("monitors")
require("modules.input")
require("modules.decoration")
require("modules.animations")
require("modules.binds")
require("modules.ryoshot")
require("modules.window_rules")
require("modules.fullscreen")
require("modules.autostart")

pcall(require, "modules.private")

-- GhostType hotkey (managed by the app)
pcall(require, "ghosttype")
