title    Ryoku Linux installer (%ARCH%, UEFI) (copy to RAM, slow USB)
sort-key 03
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% cow_spacesize=1G quiet loglevel=3 console=ttyS0,115200 console=tty0 copytoram
