$background = rgb(141218)
$surface = rgb(211f24)
$surface_container = rgb(2b292f)
$primary = rgb(d0bcfe)
$secondary = rgb(ccc2db)
$tertiary = rgb(efb8c7)
$outline = rgb(948f99)
$shadow = rgba(00000099)
