-- Managed by ryoku-gpu. Empty by default: Hyprland uses its own GPU selection.
--
-- On multi-GPU machines (a discrete Radeon/GeForce beside the CPU's integrated
-- GPU), `ryoku-gpu persist` rewrites this file with an hl.env("AQ_DRM_DEVICES", ...)
-- call that pins the strongest GPU as Hyprland's primary renderer, so the desktop
-- renders on the powerful GPU instead of a weak iGPU the monitor may be wired to.
-- It runs automatically at install and from `ryoku-doctor`; run it by hand with:
--
--   ryoku-gpu persist      # pin the discrete GPU (run ryoku-gpu detect first)
--   ryoku-gpu disable      # reset to Hyprland's default selection
--
-- Changes take effect on the next Hyprland login (the env is read at start).
