-- Generated by HyprMod
--
-- HyprMod (Settings > Hyprland settings) manages this file. The defaults below are
-- the Ryoku look-and-feel seed; HyprMod rewrites them when you change settings there.
-- Border/group colors are intentionally NOT set here so the active theme's palette
-- (colors.lua) drives them; set a border in HyprMod to override.

hl.config({
    decoration = {
        active_opacity = 0.78,
        blur = {
            brightness = 1.0,
            contrast = 1.0,
            passes = 2,
            size = 5,
            vibrancy = 0.0,
            vibrancy_darkness = 0.0,
        },
        dim_inactive = true,
        dim_strength = 0.05,
        fullscreen_opacity = 0.7,
        inactive_opacity = 0.8,
        rounding = 10,
        shadow = {
            range = 12,
            render_power = 4,
        },
    },
})

hl.env("XCURSOR_THEME", "Bibata-Modern-Classic")
hl.env("XCURSOR_SIZE", "24")

hl.curve("ryoku", { type = "bezier", points = { {0.0, 0.201}, {0.056, 1.167} } })

hl.animation({
    leaf = "windowsIn",
    enabled = true,
    speed = 5.0,
    bezier = "ryoku",
})
