-- LazyVim ships tokyonight, so it is the effective default. Fall back to the
-- always-present habamax if it somehow fails to load. (Upstream's ryoku-shell
-- theme is generated by ryoku-shell and does not exist in this slim build.)
local function ryoku_colorscheme()
  if pcall(vim.cmd.colorscheme, "tokyonight-night") then
    return
  end
  vim.cmd.colorscheme("habamax")
end

return {
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = ryoku_colorscheme,
    },
  },
}
