-- lazyvim ships tokyonight = effective default. fall back to habamax (always
-- present) if it somehow fails to load. (upstream's ryoku-shell theme is
-- generated by ryoku-shell, not in this slim build.)
local function ryoku_colorscheme()
  if pcall(vim.cmd.colorscheme, "tokyonight-night") then
    return
  end
  vim.cmd.colorscheme("habamax")
end

return {
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = ryoku_colorscheme,
    },
  },
}
