if status is-interactive
  # No greeting
  set -g fish_greeting

  if not set -q RYOKU_EDITOR
    set -gx RYOKU_EDITOR nvim
  end
  if not set -q EDITOR
    set -gx EDITOR $RYOKU_EDITOR
  end
  if not set -q VISUAL
    set -gx VISUAL $EDITOR
  end
  if not set -q SUDO_EDITOR
    set -gx SUDO_EDITOR $VISUAL
  end
  set -gx BAT_THEME ansi

  if test -d "$HOME/.local/bin"; and not contains -- "$HOME/.local/bin" $PATH
    set -gx PATH "$HOME/.local/bin" $PATH
  end
  if not set -q RYOKU_PATH; and test -d "$HOME/.local/share/ryoku"
    set -gx RYOKU_PATH "$HOME/.local/share/ryoku"
  end
  if set -q RYOKU_PATH; and test -d "$RYOKU_PATH/bin"; and not contains -- "$RYOKU_PATH/bin" $PATH
    set -gx PATH "$RYOKU_PATH/bin" $PATH
  end

  # Activate mise so its managed runtimes (node, python, go, rust, ...) land on
  # PATH. Without this, tools installed via `mise use -g` (the path Ryoku's
  # dev-env installers use) live in the mise data dir and fish reports them as
  # missing / "not on PATH".
  if command -v mise >/dev/null 2>&1
    mise activate fish | source
  end

  # Apply terminal color sequences generated by the shell theme service.
  if test -f ~/.local/state/quickshell/user/generated/terminal/sequences.txt
    cat ~/.local/state/quickshell/user/generated/terminal/sequences.txt
  end

  # Show the Ryoku startup logo whenever an interactive terminal opens.
  if command -v ryoku-fastfetch >/dev/null 2>&1
    ryoku-fastfetch
  end

  # Use starship prompt.
  if command -v starship >/dev/null 2>&1
    starship init fish | source
  end

  # Directory jumper (z / zi).
  if command -v zoxide >/dev/null 2>&1
    zoxide init fish | source
  end

  # fzf key bindings (Ctrl-R history, Ctrl-T files, Alt-C cd).
  if command -v fzf >/dev/null 2>&1
    fzf --fish | source
  end

  alias clear "printf '\033[2J\033[3J\033[1;1H'"
  alias celar "printf '\033[2J\033[3J\033[1;1H'"
  alias claer "printf '\033[2J\033[3J\033[1;1H'"
  if command -v eza >/dev/null 2>&1
    alias ls 'eza --icons'
  end
  alias q 'qs -c ryoku-shell'
end
