if status is-interactive
  # No greeting
  set -g fish_greeting

  if not set -q RYOKU_EDITOR
    set -gx RYOKU_EDITOR nvim
  end
  if not set -q EDITOR
    set -gx EDITOR $RYOKU_EDITOR
  end
  if not set -q VISUAL
    set -gx VISUAL $EDITOR
  end
  if not set -q SUDO_EDITOR
    set -gx SUDO_EDITOR $VISUAL
  end

  if not set -q RYOKU_PATH; and test -d "$HOME/.local/share/ryoku"
    set -gx RYOKU_PATH "$HOME/.local/share/ryoku"
  end
  if set -q RYOKU_PATH; and test -d "$RYOKU_PATH/bin"; and not contains -- "$RYOKU_PATH/bin" $PATH
    set -gx PATH "$RYOKU_PATH/bin" $PATH
  end

  # Apply terminal color sequences generated by the shell theme service.
  if test -f ~/.local/state/quickshell/user/generated/terminal/sequences.txt
    cat ~/.local/state/quickshell/user/generated/terminal/sequences.txt
  end

  # Show the Ryoku startup logo whenever an interactive terminal opens.
  if command -v ryoku-fastfetch >/dev/null 2>&1
    ryoku-fastfetch
  end

  # Use starship prompt.
  if command -v starship >/dev/null 2>&1
    starship init fish | source
  end

  alias clear "printf '\033[2J\033[3J\033[1;1H'"
  alias celar "printf '\033[2J\033[3J\033[1;1H'"
  alias claer "printf '\033[2J\033[3J\033[1;1H'"
  if command -v eza >/dev/null 2>&1
    alias ls 'eza --icons'
  end
  alias q 'qs -c ryoku-shell'
end
