if status is-interactive
  # No greeting
  set -g fish_greeting

  if not set -q RYOKU_EDITOR
    set -gx RYOKU_EDITOR nvim
  end
  if not set -q EDITOR
    set -gx EDITOR $RYOKU_EDITOR
  end
  if not set -q VISUAL
    set -gx VISUAL $EDITOR
  end
  if not set -q SUDO_EDITOR
    set -gx SUDO_EDITOR $VISUAL
  end

  # Apply terminal color sequences generated by the shell theme service.
  if test -f ~/.local/state/quickshell/user/generated/terminal/sequences.txt
    cat ~/.local/state/quickshell/user/generated/terminal/sequences.txt
  end

  # Show the Ryoku startup logo once for each Kitty window/split.
  if command -v ryoku-fastfetch >/dev/null 2>&1; and test "$TERM" = "xterm-kitty"
    set -l ryoku_fastfetch_key "kitty:$KITTY_WINDOW_ID"
    if test "$RYOKU_FASTFETCH_SHOWN_FOR" != "$ryoku_fastfetch_key"
      set -gx RYOKU_FASTFETCH_SHOWN_FOR "$ryoku_fastfetch_key"
      ryoku-fastfetch
    end
  end

  # Use starship prompt.
  if command -v starship >/dev/null 2>&1
    starship init fish | source
  end

  alias clear "printf '\033[2J\033[3J\033[1;1H'"
  alias celar "printf '\033[2J\033[3J\033[1;1H'"
  alias claer "printf '\033[2J\033[3J\033[1;1H'"
  if command -v eza >/dev/null 2>&1
    alias ls 'eza --icons'
  end
  alias q 'qs -c ryoku-shell'
end
