#!/bin/bash
# neovim_themegen.sh - writes Ryoku's local LazyVim colorscheme.
#
# Usage: neovim_themegen.sh <palette.json> <terminal.json> <plugin_dir>
set -euo pipefail

PALETTE_FILE="${1:?Usage: $0 <palette.json> <terminal.json> <plugin_dir>}"
TERMINAL_FILE="${2:?}"
NEOVIM_PLUGIN_DIR="${3:?}"

NEOVIM_CONFIG_DIR="$(dirname "$(dirname "$NEOVIM_PLUGIN_DIR")")"
NEOVIM_COLORS_DIR="$NEOVIM_CONFIG_DIR/colors"
# Local colorscheme target: colors/ryoku-shell.lua
NEOVIM_COLORS_FILE="$NEOVIM_COLORS_DIR/ryoku-shell.lua"

json_value() {
  local file="$1" key="$2" fallback="$3" value

  value=$(jq -r --arg key "$key" --arg fallback "$fallback" '.[$key] // $fallback' "$file" 2>/dev/null || printf '%s\n' "$fallback")
  if [[ -z $value || $value == "null" ]]; then
    printf '%s\n' "$fallback"
  else
    printf '%s\n' "$value"
  fi
}

# Write file only if changed
write_if_changed() {
  local target="$1" tmp="${1}.tmp"
  cat > "$tmp"
  if [[ -f $target ]] && cmp -s "$tmp" "$target"; then
    rm -f "$tmp"
  else
    mv "$tmp" "$target"
    printf '[neovim_themegen] %s updated\n' "$(basename "$target")"
  fi
}

primary=$(json_value "$PALETTE_FILE" primary "#8aadf4")
secondary=$(json_value "$PALETTE_FILE" secondary "#8bd5ca")
tertiary=$(json_value "$PALETTE_FILE" tertiary "#c6a0f6")
background=$(json_value "$PALETTE_FILE" background "#1e1e2e")
foreground=$(json_value "$PALETTE_FILE" on_background "#cad3f5")
surface=$(json_value "$PALETTE_FILE" surface "#24273a")
surface_variant=$(json_value "$PALETTE_FILE" surface_variant "#363a4f")
on_surface=$(json_value "$PALETTE_FILE" on_surface "$foreground")
muted=$(json_value "$PALETTE_FILE" on_surface_variant "#a5adcb")
outline=$(json_value "$PALETTE_FILE" outline "#6e738d")
error=$(json_value "$PALETTE_FILE" error "#ed8796")
success=$(json_value "$TERMINAL_FILE" term2 "#a6da95")
warning=$(json_value "$TERMINAL_FILE" term3 "#eed49f")
info=$(json_value "$TERMINAL_FILE" term6 "#8bd5ca")

term0=$(json_value "$TERMINAL_FILE" term0 "#494d64")
term1=$(json_value "$TERMINAL_FILE" term1 "#ed8796")
term2=$(json_value "$TERMINAL_FILE" term2 "#a6da95")
term3=$(json_value "$TERMINAL_FILE" term3 "#eed49f")
term4=$(json_value "$TERMINAL_FILE" term4 "#8aadf4")
term5=$(json_value "$TERMINAL_FILE" term5 "#c6a0f6")
term6=$(json_value "$TERMINAL_FILE" term6 "#8bd5ca")
term7=$(json_value "$TERMINAL_FILE" term7 "#b8c0e0")
term8=$(json_value "$TERMINAL_FILE" term8 "#5b6078")
term9=$(json_value "$TERMINAL_FILE" term9 "#ed8796")
term10=$(json_value "$TERMINAL_FILE" term10 "#a6da95")
term11=$(json_value "$TERMINAL_FILE" term11 "#eed49f")
term12=$(json_value "$TERMINAL_FILE" term12 "#8aadf4")
term13=$(json_value "$TERMINAL_FILE" term13 "#c6a0f6")
term14=$(json_value "$TERMINAL_FILE" term14 "#8bd5ca")
term15=$(json_value "$TERMINAL_FILE" term15 "#cad3f5")

mkdir -p "$NEOVIM_PLUGIN_DIR" "$NEOVIM_COLORS_DIR"
write_if_changed "$NEOVIM_PLUGIN_DIR/neovim.lua" <<'PLUGEOF'
-- neovim.lua - auto-generated by Ryoku. Use 99-ryoku-user.lua for overrides.
return {
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "ryoku-shell",
    },
  },
}
PLUGEOF

write_if_changed "$NEOVIM_COLORS_FILE" <<COLORSEOF
-- ryoku-shell.lua - auto-generated by Ryoku. Use 99-ryoku-user.lua for overrides.
vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

vim.o.background = "dark"
vim.g.colors_name = "ryoku-shell"

local colors = {
  bg = "$background",
  fg = "$foreground",
  surface = "$surface",
  surface_variant = "$surface_variant",
  muted = "$muted",
  outline = "$outline",
  primary = "$primary",
  secondary = "$secondary",
  tertiary = "$tertiary",
  error = "$error",
  success = "$success",
  warning = "$warning",
  info = "$info",
  term0 = "$term0",
  term1 = "$term1",
  term2 = "$term2",
  term3 = "$term3",
  term4 = "$term4",
  term5 = "$term5",
  term6 = "$term6",
  term7 = "$term7",
  term8 = "$term8",
  term9 = "$term9",
  term10 = "$term10",
  term11 = "$term11",
  term12 = "$term12",
  term13 = "$term13",
  term14 = "$term14",
  term15 = "$term15",
}

local function hl(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

hl("Normal", { fg = "$on_surface", bg = colors.bg })
hl("NormalFloat", { fg = colors.fg, bg = colors.surface })
hl("FloatBorder", { fg = colors.outline, bg = colors.surface })
hl("FloatTitle", { fg = colors.primary, bg = colors.surface, bold = true })
hl("CursorLine", { bg = colors.surface })
hl("CursorLineNr", { fg = colors.primary, bold = true })
hl("LineNr", { fg = colors.outline })
hl("Visual", { bg = colors.surface_variant })
hl("Search", { fg = colors.bg, bg = colors.warning })
hl("IncSearch", { fg = colors.bg, bg = colors.primary })
hl("MatchParen", { fg = colors.primary, bold = true, underline = true })
hl("Pmenu", { fg = colors.fg, bg = colors.surface })
hl("PmenuSel", { fg = colors.bg, bg = colors.primary, bold = true })
hl("StatusLine", { fg = colors.fg, bg = colors.surface })
hl("StatusLineNC", { fg = colors.muted, bg = colors.surface })
hl("WinSeparator", { fg = colors.outline })
hl("Comment", { fg = colors.muted, italic = true })
hl("Constant", { fg = colors.tertiary })
hl("String", { fg = colors.success })
hl("Character", { fg = colors.success })
hl("Number", { fg = colors.tertiary })
hl("Boolean", { fg = colors.tertiary })
hl("Identifier", { fg = colors.fg })
hl("Function", { fg = colors.primary, bold = true })
hl("Statement", { fg = colors.secondary })
hl("Keyword", { fg = colors.secondary, italic = true })
hl("Type", { fg = colors.warning })
hl("Special", { fg = colors.info })
hl("Underlined", { fg = colors.primary, underline = true })
hl("Error", { fg = colors.error })
hl("Todo", { fg = colors.bg, bg = colors.warning, bold = true })
hl("DiagnosticError", { fg = colors.error })
hl("DiagnosticWarn", { fg = colors.warning })
hl("DiagnosticInfo", { fg = colors.info })
hl("DiagnosticHint", { fg = colors.secondary })
hl("GitSignsAdd", { fg = colors.success })
hl("GitSignsChange", { fg = colors.warning })
hl("GitSignsDelete", { fg = colors.error })
hl("LazyNormal", { fg = colors.fg, bg = colors.bg })
hl("SnacksDashboardHeader", { fg = colors.primary, bold = true })
hl("SnacksDashboardDesc", { fg = colors.fg })
hl("SnacksDashboardKey", { fg = colors.secondary, bold = true })
hl("SnacksDashboardIcon", { fg = colors.tertiary })
hl("NoiceCmdlinePopupBorder", { fg = colors.primary })
hl("WhichKey", { fg = colors.primary })

vim.g.terminal_color_0 = colors.term0
vim.g.terminal_color_1 = colors.term1
vim.g.terminal_color_2 = colors.term2
vim.g.terminal_color_3 = colors.term3
vim.g.terminal_color_4 = colors.term4
vim.g.terminal_color_5 = colors.term5
vim.g.terminal_color_6 = colors.term6
vim.g.terminal_color_7 = colors.term7
vim.g.terminal_color_8 = colors.term8
vim.g.terminal_color_9 = colors.term9
vim.g.terminal_color_10 = colors.term10
vim.g.terminal_color_11 = colors.term11
vim.g.terminal_color_12 = colors.term12
vim.g.terminal_color_13 = colors.term13
vim.g.terminal_color_14 = colors.term14
vim.g.terminal_color_15 = colors.term15
COLORSEOF

# Clean up stale files from previous versions
stale_prefix="i""nir"
for stale in \
  "$NEOVIM_PLUGIN_DIR/${stale_prefix}-colorscheme.lua" \
  "$NEOVIM_PLUGIN_DIR/${stale_prefix}_theme.lua" \
  "$NEOVIM_CONFIG_DIR/colors/${stale_prefix}.lua"
do
  if [[ -f "$stale" ]]; then
    rm -f "$stale"
    printf '[neovim_themegen] removed stale: %s\n' "$(basename "$stale")"
  fi
done
