#!/bin/bash
set -euo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/lib/module-runtime.sh"
COLOR_MODULE_ID="rmpc"

APP_PALETTE_FILE="$STATE_DIR/user/generated/app-palette.json"
PALETTE_FILE="$STATE_DIR/user/generated/palette.json"
RMPC_THEMES_DIR="$HOME/.config/rmpc/themes"
RMPC_THEME_FILE="$RMPC_THEMES_DIR/ryoku.ron"
RMPC_CONFIG_FILE="$HOME/.config/rmpc/config.ron"

main() {
  local enabled
  enabled="$(config_json 'if .appearance.wallpaperTheming | has("enableRmpc") then .appearance.wallpaperTheming.enableRmpc else true end' true)"
  [[ "$enabled" == "true" ]] || exit 0

  # Only run if rmpc is installed AND the user has the music profile config.
  # Either condition missing -> the user has not opted in.
  command -v rmpc >/dev/null 2>&1 || exit 0
  [[ -f "$RMPC_CONFIG_FILE" ]] || exit 0

  local palette
  if [[ -f "$APP_PALETTE_FILE" ]]; then
    palette="$APP_PALETTE_FILE"
  elif [[ -f "$PALETTE_FILE" ]]; then
    palette="$PALETTE_FILE"
  else
    log_module "no palette file available"
    exit 0
  fi

  mkdir -p "$RMPC_THEMES_DIR"

  local bg on_bg fg surface highlight on_accent accent muted border
  bg="$(jq -r '.background // "#131313"' "$palette")"
  on_bg="$(jq -r '.on_background // "#E2E2E2"' "$palette")"
  fg="$(jq -r '.on_surface // .on_background // "#E2E2E2"' "$palette")"
  surface="$(jq -r '.surface_container // .surface // "#1B1B1B"' "$palette")"
  highlight="$(jq -r '.primary // "#FFFFFF"' "$palette")"
  on_accent="$(jq -r '.on_primary // "#1B1B1B"' "$palette")"
  accent="$(jq -r '.primary_container // .primary // "#D4D4D4"' "$palette")"
  muted="$(jq -r '.on_surface_variant // "#C6C6C6"' "$palette")"
  border="$(jq -r '.surface_variant // "#474747"' "$palette")"

  cat > "$RMPC_THEME_FILE" <<EOF
// Auto-generated by ryoku (95-rmpc.sh). Edits will be overwritten on
// the next wallpaper change. Disable in Settings -> Themes -> Wallpaper
// Theming if you want to manage this file yourself.
#![enable(implicit_some)]
(
    default_album_art_path: None,
    show_song_table_header: true,
    draw_borders: true,
    background_color: "${bg}",
    text_color: "${fg}",
    header_background_color: "${surface}",
    modal_background_color: "${surface}",
    preview_label_style: ( fg: "${muted}" ),
    preview_metadata_group_style: ( fg: "${highlight}", modifiers: "Bold" ),
    tab_bar: ( enabled: true,
        active_style: ( fg: "${on_accent}", bg: "${highlight}", modifiers: "Bold" ),
        inactive_style: ( fg: "${muted}" ),
    ),
    highlighted_item_style: ( fg: "${highlight}", modifiers: "Bold" ),
    current_item_style: ( fg: "${on_accent}", bg: "${highlight}", modifiers: "Bold" ),
    borders_style: ( fg: "${border}" ),
    highlight_border_style: ( fg: "${highlight}" ),
    symbols: ( song: "♪", dir: "📁", marker: "" ),
    progress_bar: (
        symbols: ["█", "█", "█", "▒", " "],
        track_style: ( fg: "${border}" ),
        elapsed_style: ( fg: "${highlight}" ),
        thumb_style: ( fg: "${highlight}", bg: "${surface}" ),
    ),
    scrollbar: (
        symbols: ["│", "█", "▲", "▼"],
        track_style: ( fg: "${border}" ),
        ends_style: ( fg: "${accent}" ),
        thumb_style: ( fg: "${highlight}" ),
    ),
    song_table_format: [
        ( prop: ( kind: Property(Title), default: ( kind: Property(Filename) ) ), label: "Title", width_percent: 35 ),
        ( prop: ( kind: Property(Artist), default: ( kind: Text("Unknown") ) ), label: "Artist", width_percent: 30 ),
        ( prop: ( kind: Property(Album), default: ( kind: Text("Unknown") ) ), label: "Album", width_percent: 25 ),
        ( prop: ( kind: Property(Duration), default: ( kind: Text("-") ) ), label: "Duration", width_percent: 10 ),
    ],
)
EOF

  log_module "wrote $RMPC_THEME_FILE"
  # The user's rmpc config has enable_config_hot_reload: true so rmpc
  # watches this file and picks it up on the next status tick. No
  # explicit reload signal needed.
}

main "$@"
