### Read more at config document: https://github.com/limine-bootloader/limine/blob/trunk/CONFIG.md
#timeout: 3
default_entry: 2
interface_branding: Ryoku Bootloader
interface_branding_color: 2
hash_mismatch_panic: no

term_background: 171717
backdrop: 171717

# Terminal colors (Greek Noir palette, matches themes/greek-noir)
term_palette: 171717;aeab94;F25623;4D4D4D;88A57D;F56E0F;8A8A8A;bcbfbc
term_palette_bright: 333333;aeab94;F25623;4D4D4D;88A57D;F56E0F;8A8A8A;757d75

# Text colors
term_foreground: CCD0CF
term_foreground_bright: CCD0CF
term_background_bright: 333333
