# Laptop multimedia keys for volume and LCD brightness (with OSD)
bindeld = ,XF86AudioRaiseVolume, Volume up, exec, ryoku-swayosd-client --output-volume raise
bindeld = ,XF86AudioLowerVolume, Volume down, exec, ryoku-swayosd-client --output-volume lower
bindeld = ,XF86AudioMute, Mute, exec, ryoku-swayosd-client --output-volume mute-toggle
bindeld = ,XF86AudioMicMute, Mute microphone, exec, ryoku-cmd-mic-mute
bindeld = ,XF86MonBrightnessUp, Brightness up, exec, ryoku-brightness-display +5%
bindeld = ,XF86MonBrightnessDown, Brightness down, exec, ryoku-brightness-display 5%-
bindeld = ,XF86KbdBrightnessUp, Keyboard brightness up, exec, ryoku-brightness-keyboard up
bindeld = ,XF86KbdBrightnessDown, Keyboard brightness down, exec, ryoku-brightness-keyboard down
bindld = ,XF86KbdLightOnOff, Keyboard backlight cycle, exec, ryoku-brightness-keyboard cycle
bindld = ,XF86TouchpadToggle, Toggle touchpad, exec, ryoku-toggle-touchpad
bindld = ,XF86TouchpadOn, Enable touchpad, exec, ryoku-toggle-touchpad on
bindld = ,XF86TouchpadOff, Disable touchpad, exec, ryoku-toggle-touchpad off

# Precise 1% multimedia adjustments with Alt modifier
bindeld = ALT, XF86AudioRaiseVolume, Volume up precise, exec, ryoku-swayosd-client --output-volume +1
bindeld = ALT, XF86AudioLowerVolume, Volume down precise, exec, ryoku-swayosd-client --output-volume -1
bindeld = ALT, XF86MonBrightnessUp, Brightness up precise, exec, ryoku-brightness-display +1%
bindeld = ALT, XF86MonBrightnessDown, Brightness down precise, exec, ryoku-brightness-display 1%-

# Requires playerctl
bindld = , XF86AudioNext, Next track, exec, ryoku-swayosd-client --playerctl next
bindld = , XF86AudioPause, Pause, exec, ryoku-swayosd-client --playerctl play-pause
bindld = , XF86AudioPlay, Play, exec, ryoku-swayosd-client --playerctl play-pause
bindld = , XF86AudioPrev, Previous track, exec, ryoku-swayosd-client --playerctl previous

# Switch audio output with Super + Mute
bindld = SUPER, XF86AudioMute, Switch audio output, exec, ryoku-cmd-audio-switch
