# Menus
bindd = SUPER, SPACE, Launch apps, exec, qs -c ryoku ipc call popups toggleLauncher
bindd = SUPER, D, Toggle dashboard, exec, qs -c ryoku ipc call popups toggleDashboard
bindd = SUPER CTRL, C, Capture menu, exec, ryoku-menu capture
bindd = SUPER CTRL, O, Toggle menu, exec, ryoku-menu toggle
bindd = SUPER CTRL, H, Hardware menu, exec, ryoku-menu hardware
bindd = SUPER ALT, SPACE, Ryoku menu, exec, ryoku-menu
bindd = SUPER SHIFT, code:201, Ryoku menu, exec, ryoku-menu
bindd = SUPER, ESCAPE, System menu, exec, ryoku-menu system
bindld = , XF86PowerOff, Power menu, exec, ryoku-menu system
bindd = SUPER, K, Show key bindings, exec, ryoku-menu-keybindings
bindd = , XF86Calculator, Calculator, exec, gnome-calculator

# Aesthetics
bindd = SUPER SHIFT, SPACE, Toggle top bar, exec, ryoku-toggle-waybar
bindd = SUPER CTRL, SPACE, Theme background menu, exec, qs -c ryoku ipc call popups toggleWallpaper
bindd = SUPER SHIFT CTRL, SPACE, Theme menu, exec, ryoku-menu theme
bindd = SUPER, BACKSPACE, Toggle window transparency, exec, ryoku-hyprland-active-window-transparency-toggle
bindd = SUPER SHIFT, BACKSPACE, Toggle window gaps, exec, ryoku-hyprland-window-gaps-toggle
bindd = SUPER CTRL, BACKSPACE, Toggle single-window square aspect, exec, ryoku-hyprland-window-single-square-aspect-toggle

# Notifications
bindd = SUPER, COMMA, Dismiss last notification, exec, makoctl dismiss
bindd = SUPER SHIFT, COMMA, Dismiss all notifications, exec, makoctl dismiss --all
bindd = SUPER CTRL, COMMA, Toggle silencing notifications, exec, ryoku-toggle-notification-silencing
bindd = SUPER ALT, COMMA, Invoke last notification, exec, makoctl invoke
bindd = SUPER SHIFT ALT, COMMA, Restore last notification, exec, makoctl restore

# Toggles
bindd = SUPER CTRL, I, Toggle locking on idle, exec, ryoku-toggle-idle
bindd = SUPER CTRL, N, Toggle nightlight, exec, ryoku-toggle-nightlight
bindd = SUPER CTRL, Delete, Toggle laptop display, exec, ryoku-hyprland-monitor-internal toggle
bindl = , switch:on:Lid Switch, exec, ryoku-hyprland-monitor-internal off
bindl = , switch:off:Lid Switch, exec, ryoku-hyprland-monitor-internal on

# Control Apple Display brightness
bindd = CTRL, F1, Apple Display brightness down, exec, ryoku-brightness-display-apple -5000
bindd = CTRL, F2, Apple Display brightness up, exec, ryoku-brightness-display-apple +5000
bindd = SHIFT CTRL, F2, Apple Display full brightness, exec, ryoku-brightness-display-apple +60000

# Captures
bindd = , PRINT, Screenshot, exec, ryoku-cmd-screenshot
bindd = ALT, PRINT, Screenrecording, exec, ryoku-menu screenrecord
bindd = SUPER, PRINT, Color picker, exec, pkill hyprpicker || hyprpicker -a

# File sharing
bindd = SUPER CTRL, S, Share, exec, ryoku-menu share

# Waybar-less information
bindd = SUPER CTRL ALT, T, Show time, exec, notify-send -u low "    $(date +"%A %H:%M  ·  %d %B %Y  ·  Week %V")"
bindd = SUPER CTRL ALT, B, Show battery remaining, exec, notify-send -u low "$(ryoku-battery-status)"

# Control panels
bindd = SUPER CTRL, A, Audio controls, exec, ryoku-launch-audio
bindd = SUPER CTRL, B, Bluetooth controls, exec, ryoku-launch-bluetooth
bindd = SUPER CTRL, W, Wifi controls, exec, ryoku-launch-wifi
bindd = SUPER CTRL, T, Activity, exec, ryoku-launch-tui btop

# Dictation
bindd = SUPER CTRL, X, Toggle dictation, exec, voxtype record toggle

# Zoom
bindd = SUPER CTRL, Z, Zoom in, exec, hyprctl keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '.float + 1')
bindd = SUPER CTRL ALT, Z, Reset zoom, exec, hyprctl keyword cursor:zoom_factor 1

# Lock system
bindd = SUPER CTRL, L, Lock system, exec, ryoku-lock-screen
